// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	submitFocusRun: (request: SubmitFocusRunRequest) => typedError<SubmitFocusRunResponse, string>(__TAURI_INVOKE("submit_focus_run", { request })),
	getRunOutput: (runId: string, userId: string, personaId: string, keyHex: string) => typedError<GetRunOutputResponse, string>(__TAURI_INVOKE("get_run_output", { runId, userId, personaId, keyHex })),
	cancelRun: (runId: string, userId: string, personaId: string, keyHex: string) => typedError<null, string>(__TAURI_INVOKE("cancel_run", { runId, userId, personaId, keyHex })),
	/**
	 *  Resume a paused focus run.
	 * 
	 *  Routes by focus_runs.status (schema/outputs_001.sql CHECK — the full set
	 *  is 'initializing','running','paused','awaiting_user','awaiting_feedback',
	 *  'awaiting_extract_confirm','complete','cancelled','failed').
	 * 
	 *  awaiting_extract_confirm routing:
	 *    1. Crash-recovery replay: rows with status='confirmed' AND persisted_at IS NULL
	 *       -> replay persist_confirmed_field() + set_persisted_at() using persisted
	 *       sensitivity (never recomputed -- see load_unrecovered_rows() doc).
	 *    2. If pending > 0: re-emit extract_confirm_request push event and return.
	 *    3. If pending == 0: all candidates decided. output() is called by
	 *       submit_extract_confirm once the user submits decisions -- not from here.
	 *       Full snapshot replay for this path is deferred post-Release-1.
	 * 
	 *  complete/cancelled/failed: terminal -- there is nothing to resume, so this
	 *  returns a distinct "already finished" error rather than not_implemented,
	 *  which would incorrectly imply resume itself is the missing piece.
	 * 
	 *  awaiting_feedback: Phase 5 OUTPUT already ran and saved content (see
	 *  lifecycle.rs output()) -- Phase 6 FEEDBACK is explicitly out of scope of
	 *  the FocusRun module (lifecycle.rs module header, "out of scope for this
	 *  module (async paste-back)"). Nothing is pending execution; the caller
	 *  should fetch the already-produced output via get_run_output instead.
	 * 
	 *  awaiting_user, paused, running, initializing: genuinely not_implemented
	 *  (unchanged stub behaviour). All four are blocked on the same structural
	 *  gap, not a missing switch statement: FocusRun::new() requires
	 *  `user_input`, and every step's prompt render threads it through
	 *  StepContext (lifecycle.rs execute_step()) -- but user_input is never
	 *  persisted anywhere (not on focus_runs, not in focus_run_snapshots). There
	 *  is currently no way to reconstruct a live FocusRun to re-enter execute()
	 *  for any of these four statuses without first adding somewhere to store
	 *  it, which is a schema change, not a resume_run fix. See each match arm
	 *  below for the state-specific detail on top of that shared blocker.
	 */
	resumeRun: (request: ResumeRunRequest) => typedError<string, string>(__TAURI_INVOKE("resume_run", { request })),
	submitConsentDecision: (request: SubmitConsentDecisionRequest) => typedError<null, string>(__TAURI_INVOKE("submit_consent_decision", { request })),
	submitFloorConsentDecision: (request: SubmitFloorConsentDecisionRequest) => typedError<null, string>(__TAURI_INVOKE("submit_floor_consent_decision", { request })),
	submitElementConsentDecision: (request: SubmitElementConsentDecisionRequest) => typedError<null, string>(__TAURI_INVOKE("submit_element_consent_decision", { request })),
	/**
	 *  items.id=92 -- process the user's proceed/cancel answer to a friction-gate
	 *  block returned by commands::persona::update_focus_settings.
	 * 
	 *  On "cancel": records the decision only. No settings change is applied --
	 *  the Focus keeps its prior settings exactly as they were.
	 * 
	 *  On "proceed": records the decision, THEN applies original_request via
	 *  focus_settings_store::update_focus_settings directly (NOT by calling
	 *  commands::persona::update_focus_settings again, which would immediately
	 *  re-trip the same gate check this command exists to get past). Both
	 *  writes happen in this one call -- the frontend does not make a second
	 *  settings-update request itself.
	 * 
	 *  Re-validates original_request's tier bounds before applying, mirroring
	 *  update_focus_settings's own guard -- this command is a second entry
	 *  point into the same mutation and must not skip a check the first entry
	 *  point enforces, even though the friction-gate values themselves were
	 *  already validated once when update_focus_settings first computed them.
	 */
	submitFrictionGateDecision: (request: SubmitFrictionGateDecisionRequest) => typedError<{
	focus_id: string,
	focus_profile: string,
	context_flow: string,
	library_visibility: string,
	privacy_tier: number,
	max_permitted_tier: number,
	updated_at: string,
} | null, string>(__TAURI_INVOKE("submit_friction_gate_decision", { request })),
	/**
	 *  Process user decisions for extract-and-confirm candidates (item 20).
	 * 
	 *  Validation: confirmed==true with confirmed_value==None rejects entire call
	 *  before any DB mutation (IPC contract violation).
	 * 
	 *  Processing set: pending candidates + confirmed-but-unpersisted (crash-recovery
	 *  targets). Both are included so retries can complete interrupted work.
	 * 
	 *  Write sequence per confirmed pending candidate:
	 *    1. get_candidate_fields()    -> read field_name + sensitivity from outputs.db
	 *    2. persist_confirmed_field() -> COMMIT personal.db (idempotent upsert)
	 *    3. mark_candidate_decided()  -> COMMIT outputs.db (sets confirmed_at)
	 *    4. set_persisted_at()        -> COMMIT outputs.db
	 * 
	 *  Ordering rationale: personal.db write first so that on retry, if step 3/4
	 *  failed, we re-attempt an idempotent upsert rather than leaving candidate
	 *  marked decided with no persisted field.
	 * 
	 *  After all decisions: verify no confirmed-but-unpersisted rows remain,
	 *  then set focus_runs.status='complete' and emit run_status_update.
	 */
	submitExtractConfirm: (request: SubmitExtractConfirmRequest) => typedError<null, string>(__TAURI_INVOKE("submit_extract_confirm", { request })),
	/**
	 *  Pre-Focus-start query: which cross_persona_export=true entity_facts rows
	 *  exist for this persona and require per-session confirmation before a
	 *  Focus run may include them (decisions.id=546, decisions.id=639, items.id=27).
	 * 
	 *  Called by the frontend BEFORE FocusRun::new() is constructed. Read-only --
	 *  this command does not write a decision anywhere. The frontend shows a
	 *  confirmation UI for the returned facts, then passes the fact_ids the user
	 *  approved into SubmitFocusRunRequest.confirmed_cross_persona_fact_ids.
	 *  Facts not included there are treated as declined by
	 *  apply_entity_fact_provenance_check() -- omitted from context, not a
	 *  hard block (Jason, this session: declining one fact should not block
	 *  the whole run).
	 */
	getPendingCrossPersonaConfirmations: (request: GetPendingCrossPersonaConfirmationsRequest) => typedError<PendingCrossPersonaFact[], string>(__TAURI_INVOKE("get_pending_cross_persona_confirmations", { request })),
	/**
	 *  PG_GATE_3, invoked against a drafted Tier-3-starter message
	 *  (messages.gate3_review_status = 'drafted', written by
	 *  commands::messages::send_message's gate3_track=true path). Completes
	 *  items.id=233's remaining stub -- see the former "NO OUTBOUND PRIVACY
	 *  GUARDIAN REVIEW HAPPENS" marker this command replaces in
	 *  Tier3AccessPane.tsx for the investigation that scoped it.
	 * 
	 *  Unlike every other command in this file, this one *triggers* gate3()
	 *  rather than *responding to* an already-fired one -- gate3()'s only prior
	 *  call site was conductor/executor.rs's own step-execution loop, with no
	 *  StepContext/PersonalTrack available here.
	 * 
	 *  Parameter sourcing (fixed/derived from quick-ask.focus, not guessed):
	 *    - target_tier=3: this flow only exists ahead of Tier 3 access.
	 *    - execution_tier=1, content_sensitivity_severity=1: quick-ask.focus
	 *      declares max_routing_tier: 1 and field_requirements: [] -- no
	 *      personal fields ever flow through it. target_tier=3 alone already
	 *      forces ReviewTier::High and defeats gate3's zero-span auto-approve
	 *      path (zero_spans_safe_to_auto_approve's target_tier >= 3 arm)
	 *      regardless of severity, so this default does not weaken review.
	 *    - step_id="draft", focus_name="Quick Ask": quick-ask.focus's own step
	 *      id and display_name.
	 *    - space_max_permitted_tier: a real per-Persona focus_settings lookup,
	 *      never a constant -- missing row is a hard Err, mirroring AUTHORIZE's
	 *      own assertion (lifecycle.rs).
	 * 
	 *  Uses SqliteDisclosureLogger (FocusRun's own default logger), not
	 *  NoopLogger/TestLogger, so the write-before-surface disclosure_log entry
	 *  gate3() writes is real, not discarded.
	 * 
	 *  gate3_review_status transition: 'pending_consent' -> 'pending-review';
	 *  'approved' (PF found nothing needing review) -> 'approved'. On
	 *  'blocked'/'timeout' the row is left at 'drafted' -- gate3_review_status's
	 *  CHECK constraint has no "blocked" state, and leaving it at 'drafted'
	 *  keeps the row retry-able rather than overloading 'withheld' (a status
	 *  meaning the user declined, not that gate3 itself refused).
	 */
	requestTier3Gate3Review: (request: RequestTier3Gate3ReviewRequest) => typedError<Gate3ReviewResult, string>(__TAURI_INVOKE("request_tier3_gate3_review", { request })),
	/**
	 *  Records the user's resolution of a Privacy Guardian consent review
	 *  (pending-review -> approved | withheld). Separate from
	 *  submit_element_consent_decision: that command writes the per-span audit
	 *  record to outputs.db's consent_decisions (keyed by run_id); this one
	 *  transitions messages.db's gate3_review_status (keyed by message_id) --
	 *  two different persistence targets. The frontend calls both after the
	 *  user resolves the Privacy Guardian modal (submit_element_consent_decision
	 *  first, then this).
	 */
	resolveTier3Gate3Review: (request: ResolveTier3Gate3ReviewRequest) => typedError<null, string>(__TAURI_INVOKE("resolve_tier3_gate3_review", { request })),
	getOnboardingFocusSuggestions: (personas: string[]) => typedError<NotImplementedPlaceholder, string>(__TAURI_INVOKE("get_onboarding_focus_suggestions", { personas })),
	submitOnboardingPersonaSelection: (personas: string[]) => typedError<string[], string>(__TAURI_INVOKE("submit_onboarding_persona_selection", { personas })),
	submitOnboardingFocusSelection: (focusSelections: NotImplementedPlaceholder[]) => typedError<string[], string>(__TAURI_INVOKE("submit_onboarding_focus_selection", { focusSelections })),
	listPersonas: (userId: string) => typedError<PersonaInfo[], string>(__TAURI_INVOKE("list_personas", { userId })),
	createPersona: (request: CreatePersonaRequest) => typedError<CreatePersonaResponse, string>(__TAURI_INVOKE("create_persona", { request })),
	listFocuses: (personaId: string) => typedError<FocusInfo[], string>(__TAURI_INVOKE("list_focuses", { personaId })),
	/**
	 *  get_focus_settings takes both persona_id and focus_id — the store key is
	 *  composite. The IPC spec lists focus_id only (higher-level abstraction).
	 */
	getFocusSettings: (personaId: string, focusId: string) => typedError<FocusInfo, string>(__TAURI_INVOKE("get_focus_settings", { personaId, focusId })),
	/**
	 *  Applies a Focus settings change directly, UNLESS the change would loosen
	 *  privacy_tier or move focus_profile to 'protected' -- in which case this
	 *  returns Err(json-serialized FrictionGateDetail) instead of applying
	 *  anything, and the frontend must route the user through
	 *  commands::consent::submit_friction_gate_decision to either apply the
	 *  change (decision="proceed") or drop it (decision="cancel"). See module
	 *  header for the full flow and the tier-direction note.
	 * 
	 *  The error string is JSON (FrictionGateDetail serialized), not a plain
	 *  message -- distinguishable from every other error this command can
	 *  return (validation failures, not_found) by attempting a JSON parse.
	 *  A frontend that doesn't parse it still gets a readable-enough string,
	 *  but the structured shape is what submit_friction_gate_decision expects
	 *  to be built from.
	 */
	updateFocusSettings: (request: UpdateFocusSettingsRequest) => typedError<FocusInfo, string>(__TAURI_INVOKE("update_focus_settings", { request })),
	getActiveBoard: (userId: string, personaId: string, keyHex: string) => typedError<ActiveBoardResponse, string>(__TAURI_INVOKE("get_active_board", { userId, personaId, keyHex })),
	getTopicList: (focusId: string, userId: string, personaId: string, keyHex: string) => typedError<TopicInfo[], string>(__TAURI_INVOKE("get_topic_list", { focusId, userId, personaId, keyHex })),
	updateTopicState: (request: UpdateTopicStateRequest) => typedError<null, string>(__TAURI_INVOKE("update_topic_state", { request })),
	getPersonalFields: (personaId: string, userId: string, keyHex: string) => typedError<PersonalFieldInfo[], string>(__TAURI_INVOKE("get_personal_fields", { personaId, userId, keyHex })),
	updatePersonalField: (request: UpdatePersonalFieldRequest) => typedError<PersonalFieldInfo, string>(__TAURI_INVOKE("update_personal_field", { request })),
	getVoiceProfile: (personaId: string, userId: string, keyHex: string) => typedError<VoiceProfileInfo, string>(__TAURI_INVOKE("get_voice_profile", { personaId, userId, keyHex })),
	/**
	 *  Lists active outputs, optionally filtered by focus_id, topic_id, and/or
	 *  output_type. Wired to output_store::list_outputs() (items.id=91, part 1).
	 * 
	 *  Enforces focus_settings.focus_profile visibility on top of output_store's
	 *  results -- outputs owned by a 'protected' Focus are excluded (items.id=230).
	 *  See module header.
	 */
	listOutputs: (userId: string, personaId: string, keyHex: string, focusId: string | null, topicId: string | null, outputType: string | null) => typedError<OutputInfo[], string>(__TAURI_INVOKE("list_outputs", { userId, personaId, keyHex, focusId, topicId, outputType })),
	/**
	 *  Enforces focus_settings.focus_profile visibility -- an output owned by a
	 *  'protected' Focus returns the same "not_found" error a genuinely missing
	 *  id would (items.id=230); a Protected output must not be distinguishable
	 *  from a nonexistent one by its error.
	 */
	getOutput: (outputId: string, userId: string, personaId: string, keyHex: string) => typedError<OutputInfo, string>(__TAURI_INVOKE("get_output", { outputId, userId, personaId, keyHex })),
	/**
	 *  Deletes an output (items.id=91, part 2, complete 2026-07-26). Soft-delete
	 *  only -- content is zeroed and status set to 'deleted'; the row is never
	 *  hard-deleted (architecture Section 3.4, output_store::delete_output).
	 * 
	 *  deep_purge: accepted for command-contract stability but NOT implemented.
	 *  Passing Some(true) returns Err("deep_purge_not_implemented"). See
	 *  output_store::delete_output's doc comment for why this is deliberately
	 *  out of scope for R1.
	 */
	deleteOutput: (outputId: string, userId: string, personaId: string, keyHex: string, deepPurge: boolean | null) => typedError<null, string>(__TAURI_INVOKE("delete_output", { outputId, userId, personaId, keyHex, deepPurge })),
	/**
	 *  Thin IPC wrapper -- the actual system-clipboard write via
	 *  tauri-plugin-clipboard-manager. See prepare_clipboard_copy for the real
	 *  (tested) logic.
	 */
	copyOutputToClipboard: (outputId: string, userId: string, personaId: string, keyHex: string) => typedError<null, string>(__TAURI_INVOKE("copy_output_to_clipboard", { outputId, userId, personaId, keyHex })),
	getFocusBuilderSession: (focusId: string | null) => typedError<NotImplementedPlaceholder, string>(__TAURI_INVOKE("get_focus_builder_session", { focusId })),
	submitFocusBuilderStep: (sessionId: string, input: NotImplementedPlaceholder) => typedError<NotImplementedPlaceholder, string>(__TAURI_INVOKE("submit_focus_builder_step", { sessionId, input })),
	/**
	 *  Report configuration state for a Tier 2 provider. Returns
	 *  configured=false (not an error) when no key is set yet -- an
	 *  unconfigured provider is a normal, expected state, not a failure.
	 */
	getTier2Config: (provider: string) => typedError<Tier2Config, string>(__TAURI_INVOKE("get_tier2_config", { provider })),
	/**  Set (or replace) the credential for a Tier 2 provider, user-global scope. */
	setTier2Provider: (provider: string, apiKey: string) => typedError<null, string>(__TAURI_INVOKE("set_tier2_provider", { provider, apiKey })),
	/**
	 *  Set (or clear, with `provider: None`) the current user's Tier 2 provider
	 *  preference -- distinct from set_tier2_provider above, which stores a
	 *  credential. This is the "which provider should QR actually use" choice
	 *  executor.rs reads via user_store::get_tier2_provider_preference
	 *  (items.id=253, unblocks items.id=251's read path).
	 */
	setTier2ProviderPreference: (provider: string | null) => typedError<null, string>(__TAURI_INVOKE("set_tier2_provider_preference", { provider })),
	dismissNotification: (notificationId: string) => typedError<null, string>(__TAURI_INVOKE("dismiss_notification", { notificationId })),
	login: (displayName: string, password: string) => typedError<null, string>(__TAURI_INVOKE("login", { displayName, password })),
	logout: () => typedError<null, string>(__TAURI_INVOKE("logout")),
	/**
	 *  Derive and return the current session's recovery mnemonic for one-time
	 *  display. Section 8.5's Option B: `Mnemonic::from_entropy()` on the raw
	 *  32-byte master key directly, not a wrapper key -- `Mnemonic::parse()` on
	 *  the returned phrase later recovers the exact original bytes, no
	 *  unwrapping step. Requires a resident session (KeyRegistry) the same way
	 *  tier2::get_tier2_config does; "not logged in" is the same error string
	 *  for the same reason -- there is no key to derive a mnemonic from yet.
	 */
	getRecoveryKeyDisplay: () => typedError<RecoveryKeyDisplay, string>(__TAURI_INVOKE("get_recovery_key_display")),
	getHealth: () => typedError<HealthResponse, string>(__TAURI_INVOKE("get_health")),
	getCapabilityProfile: () => typedError<CapabilityProfileResponse, string>(__TAURI_INVOKE("get_capability_profile")),
	/**
	 *  The selector screen's primary read path (TIER3_ACCESS_MODEL.md State 3,
	 *  items.id=202 piece 1's remaining wiring) -- replaces
	 *  tier3AccessConfig.ts's PLACEHOLDER_PROVIDERS stand-in array.
	 */
	listActiveProviders: () => typedError<Tier3ProviderSummary[], string>(__TAURI_INVOKE("list_active_providers")),
	/**
	 *  Opens one pane per confirmed provider selection (items.id=223's actual
	 *  trigger -- nothing in tier3_pane/ creates a pane except in response to
	 *  this). `launch_url` is looked up server-side; the frontend only ever
	 *  passes provider IDs. Best-effort across the batch: the first provider
	 *  that fails to resolve or send aborts the remaining opens rather than
	 *  silently skipping them, since a partial open would leave the selector's
	 *  own "confirmed" state and the actual open panes disagreeing about what's
	 *  open. Cookie restore (items.id=224 resolution) is a separate, narrower
	 *  best-effort layer within each iteration -- see restore_cookies_into_jar's
	 *  own doc on why that failure mode does NOT abort the batch the same way.
	 * 
	 *  Dispatch is a single `AppHandle::run_on_main_thread` call per provider
	 *  (items.id=202 real positioning fix, 2026-08-07) -- unlike the old
	 *  `EventLoopProxy::send_event`, this both queues the work AND guarantees it
	 *  runs promptly: `run_on_main_thread` is Tauri/tao's own main-thread
	 *  dispatch queue, serviced as part of GTK's ordinary main-loop operation,
	 *  not a queue that needed a *separate* explicit wake call to be noticed
	 *  (see the old design's now-deleted note here about a real, empirically
	 *  confirmed dispatch-delay bug that required exactly that workaround).
	 */
	openTier3Panes: (providerIds: string[]) => typedError<null, string>(__TAURI_INVOKE("open_tier3_panes", { providerIds })),
	/**
	 *  Closes one pane by provider ID. A no-op (not an error) if that provider
	 *  has no open pane -- `PaneManager::close_pane` already tolerates this
	 *  (pane_host.rs), and a caller racing a close against an already-closed
	 *  pane is a normal condition, not a failure. See open_tier3_panes' doc on
	 *  why a single `run_on_main_thread` call is dispatch and guaranteed-prompt
	 *  delivery in one step now. Cookie persist (items.id=224 resolution) runs
	 *  before the close is dispatched -- see persist_cookies_from_jar's own
	 *  doc; its failure is logged, never a reason this command returns an
	 *  error (the pane must still close).
	 */
	closeTier3Pane: (providerId: string) => typedError<null, string>(__TAURI_INVOKE("close_tier3_pane", { providerId })),
	/**
	 *  items.id=202 piece 4, real positioning fix 2026-08-07 -- stores the
	 *  frontend's live layout fractions (unchanged `PaneRectFraction` semantics:
	 *  fraction of the whole window's content area) and requests a redraw so the
	 *  GLArea's own `render` callback (pane_host.rs) picks up the new layout on
	 *  its very next tick. Called whenever the frontend's pane-dock region
	 *  resizes or `openPaneIds` changes (a different pane count changes the
	 *  column split even at the same dock size).
	 * 
	 *  No window-geometry query here anymore. The old version queried
	 *  `window.inner_position()`/`inner_size()` to build an absolute
	 *  `PhysicalRect` for a separate OS window to sync against -- confirmed
	 *  broken on Wayland (pinned, wrong origin/size on this dev machine's
	 *  KDE/Wayland session) and the exact code this rewrite deletes rather than
	 *  patches. Under single-window compositing every pane's target is already
	 *  expressed relative to the GLArea's own size (render.rs's `render()`
	 *  reads `PaneLayoutState` directly), so there is nothing left to query.
	 */
	setPaneLayout: (layout: PaneLayoutEntry[]) => typedError<null, string>(__TAURI_INVOKE("set_pane_layout", { layout })),
	sendMessage: (userId: string, personaId: string, keyHex: string, contextKey: string, content: string, focusId: string, gate3Track: boolean) => typedError<MessageInfo[], string>(__TAURI_INVOKE("send_message", { userId, personaId, keyHex, contextKey, content, focusId, gate3Track })),
	listMessages: (userId: string, personaId: string, keyHex: string, contextKey: string) => typedError<MessageInfo[], string>(__TAURI_INVOKE("list_messages", { userId, personaId, keyHex, contextKey })),
};

/* Types */
export type ActiveBoardResponse = {
	topics: TopicInfo[],
	/**
	 *  Placeholder -- Daily Brief not yet implemented. Will become a typed
	 *  struct when wired; serialized as JSON string in the interim.
	 */
	daily_brief: string | null,
	/**  Placeholder -- Quick Launch Dock not yet implemented. */
	quick_launch: string[],
};

export type CapabilityProfileResponse = {
	installed_models: string[],
	/**
	 *  Release 1: "pending" | "unavailable" only.
	 *  "complete" requires evaluation/scores DB port (post-Release 1).
	 *  STUB: recommended_routing omitted until scores DB is ported.
	 */
	benchmark_status: string,
};

export type CreatePersonaRequest = {
	user_id: string,
	name: string,
	persona_type: string | null,
};

export type CreatePersonaResponse = {
	persona_id: string,
};

/**  IPC gap: missing dormancy_state, last_used (post-Release 1). */
export type FocusInfo = {
	focus_id: string,
	focus_profile: string,
	context_flow: string,
	library_visibility: string,
	privacy_tier: number,
	max_permitted_tier: number,
	updated_at: string,
};

/**
 *  IPC-safe projection of Gate3Result — Gate3Result itself derives neither
 *  Serialize nor specta::Type (it's an internal gate3.rs/executor.rs return
 *  type). Field-for-field mirror; see Gate3Result's own doc comments for
 *  what each bool means.
 */
export type Gate3ReviewResult = {
	approved: boolean,
	blocked: boolean,
	pending_consent: boolean,
	timeout: boolean,
	plain_language: string | null,
};

export type GetPendingCrossPersonaConfirmationsRequest = {
	user_id: string,
	persona_id: string,
	key_hex: string,
};

export type GetRunOutputResponse = {
	content: string,
	output_type: string,
	sensitivity: string,
};

export type HealthResponse = {
	ollama: ProviderHealth,
	/**
	 *  "system" | "sidecar" | "unavailable".
	 *  Set during app setup by OllamaSidecar::ensure_available().
	 *  "unavailable" is returned during the brief startup detection window.
	 */
	ollama_source: string,
	/**
	 *  True iff an active user-global key exists for ANY Tier 2 provider
	 *  (mistral or groq) -- a capability-status signal ("is Tier 2 usable
	 *  at all," e.g. for an onboarding nudge), not a report of which
	 *  provider is active. Provider *selection* at execution time is a
	 *  separate, currently-unwired concern (executor.rs hardcodes Groq
	 *  today; users.tier2_provider_preference exists in schema but nothing
	 *  reads it yet) -- out of scope for this field, confirmed no-loss
	 *  this session: there is no per-provider consumer downstream to feed.
	 *  False, not an error, when no session is resident -- get_health must
	 *  stay callable pre-login (Ollama status has no such requirement).
	 */
	tier2_configured: boolean,
};

export type MessageInfo = {
	id: string,
	context_key: string,
	sender: string,
	content: string,
	focus_run_id: string | null,
	gate3_review_status: string | null,
	created_at: string,
};

/**
 *  Placeholder request/response shape for commands that are declared but not
 *  yet built.
 * 
 *  Why this exists (items.id=27): five stub commands
 *  (onboarding::get_onboarding_focus_suggestions,
 *  onboarding::submit_onboarding_focus_selection,
 *  focus_builder::get_focus_builder_session,
 *  focus_builder::submit_focus_builder_step, tier2::get_tier2_config)
 *  previously used serde_json::Value as an argument or return type.
 *  serde_json::Value is self-referential (Array(Vec<Value>),
 *  Object(Map<String, Value>)), and specta's TypeScript exporter recurses
 *  through it without terminating -- confirmed empirically: excluding exactly
 *  those five commands makes the export succeed, and a 64 MB stack does not
 *  help.
 * 
 *  These commands all return Err("not_implemented") today and have no designed
 *  payload shape, so serde_json::Value was a placeholder rather than a decided
 *  contract. This type says that explicitly instead. Each of the five should
 *  be given its real request/response struct when its feature is designed --
 *  this is deliberately not a contract to build against.
 * 
 *  UPDATE (items.id=185, 2026-08-02): tier2::get_tier2_config now has a real
 *  return type (commands::tier2::Tier2Config) and no longer uses this
 *  placeholder -- four of the original five remain unbuilt.
 * 
 *  UPDATE (items.id=229, 2026-08-09): auth::get_recovery_key_display also
 *  stopped using this placeholder (commands::auth::RecoveryKeyDisplay) --
 *  it was never one of the original five (it started using this type later,
 *  in commit dddc086/items.id=205, after this doc comment was written), so
 *  its removal doesn't change the "four of five" count above.
 */
export type NotImplementedPlaceholder = Record<string, never>;

export type OutputInfo = {
	id: string,
	focus_run_id: string,
	output_type: string,
	content: string,
	sensitivity: string,
	status: string,
	created_at: string,
};

/**
 *  `Vec`, not `HashMap`, to match this codebase's existing IPC-struct
 *  convention -- no command signature anywhere else uses `HashMap`.
 */
export type PaneLayoutEntry = {
	provider_id: string,
	rect: PaneRectFraction,
};

/**
 *  One pane's target region, as a fraction (0..1) of the main window's own
 *  *content* area -- not absolute screen pixels. Dimensionless on purpose:
 *  the frontend computes this from plain DOM geometry
 *  (`getBoundingClientRect()` / `window.innerWidth`/`innerHeight`), with no
 *  need for `devicePixelRatio` or a Tauri window-position API call. Under
 *  single-window compositing (items.id=202 real positioning fix,
 *  2026-08-07, see pane_host.rs) this fraction is multiplied directly
 *  against GTK's own live `GLArea` size inside `RenderState::render()` --
 *  no Rust-side window-geometry query is involved at all, so a window
 *  *move* alone stays correctly synced for free (GTK relayouts the GLArea
 *  as an ordinary child widget), and even a resize only needs the GLArea's
 *  own `resize` signal, not anything from `main.rs`.
 */
export type PaneRectFraction = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

/**
 *  IPC-safe projection of an entity_facts row pending cross-Persona
 *  confirmation (decisions.id=546, decisions.id=639, items.id=27).
 *  field_value is intentionally absent -- mirrors PersonalFieldInfo's
 *  no-raw-values convention in commands/personal.rs.
 */
export type PendingCrossPersonaFact = {
	/**
	 *  entity_facts.id -- pass this back in
	 *  SubmitFocusRunRequest.confirmed_cross_persona_fact_ids for any fact
	 *  the user approves.
	 */
	fact_id: string,
	entity_id: string | null,
	field_name: string,
	sensitivity: string,
	/**
	 *  The Persona instance this fact originated in (decisions.id=546).
	 *  Always Some for a row with cross_persona_export=true -- the DB CHECK
	 *  constraint on entity_facts (personal_001.sql) guarantees this.
	 */
	origin_persona_id: string | null,
};

/**  IPC gap: missing color, focus_count, privacy defaults (post-Release 1). */
export type PersonaInfo = {
	id: string,
	display_name: string,
	persona_type: string,
	created_at: string,
};

/**  IPC-safe projection of PersonalField. field_value is intentionally absent. */
export type PersonalFieldInfo = {
	field_name: string,
	sensitivity: string,
	/**  Abstracted display value for Tier 2 routing contexts. */
	abstraction_tier2: string,
	/**  Abstracted display value for Tier 3 routing contexts. */
	abstraction_tier3: string,
};

export type ProviderHealth = {
	provider: string,
	status: ProviderStatus,
	/**  ISO 8601 UTC string. */
	checked_at: string,
	error: string | null,
	available_models?: string[],
};

export type ProviderStatus = "available" | "degraded" | "unavailable";

/**
 *  One-time recovery mnemonic display. Never persisted anywhere past this
 *  response -- QR holds no copy of `mnemonic` or the entropy it was derived
 *  from once this call returns (Section 5/8.5 invariant).
 */
export type RecoveryKeyDisplay = {
	mnemonic: string,
};

export type RequestTier3Gate3ReviewRequest = {
	user_id: string,
	persona_id: string,
	key_hex: string,
	message_id: string,
};

export type ResolveTier3Gate3ReviewRequest = {
	user_id: string,
	persona_id: string,
	key_hex: string,
	message_id: string,
	/**
	 *  "approved" | "withheld" -- the two terminal states a resolved
	 *  consent review can reach. "drafted"/"pending-review" are gate3's own
	 *  transitions (request_tier3_gate3_review writes those), not valid
	 *  input here.
	 */
	status: string,
};

export type ResumeRunRequest = {
	run_id: string,
	user_id: string,
	persona_id: string,
	key_hex: string,
};

export type SubmitConsentDecisionRequest = {
	run_id: string,
	user_id: string,
	persona_id: string,
	key_hex: string,
	/**  "approved" | "declined" */
	decision: string,
};

export type SubmitElementConsentDecisionRequest = {
	run_id: string,
	user_id: string,
	persona_id: string,
	key_hex: string,
	/**
	 *  JSON-serialized Vec<ElementDecision> produced by the frontend.
	 *  Expected shape per element:
	 *    { "span_id": string, "decision": "generalize"|"keep_private"|"release_original",
	 *      "suggestion_text": string|null, "user_modified_text": string|null }
	 *  The command layer does not deserialize this -- it is passed through to
	 *  write_element_consent_decisions() as-is (D6-362 IPC boundary rule).
	 */
	decisions_json: string,
};

export type SubmitExtractConfirmRequest = {
	run_id: string,
	user_id: string,
	persona_id: string,
	key_hex: string,
	/**
	 *  JSON-serialized Vec<ExtractConfirmDecision>.
	 *  Shape per element:
	 *    { "candidate_id": i64, "confirmed": bool,
	 *      "extracted_value": string, "confirmed_value": string|null }
	 *  confirmed_value must be non-null when confirmed==true.
	 */
	decisions_json: string,
};

export type SubmitFloorConsentDecisionRequest = {
	run_id: string,
	user_id: string,
	persona_id: string,
	key_hex: string,
	abstraction_tier: number,
	/**  "proceed" | "cancel" */
	decision: string,
	/**  If true, saves as standing floor consent preference (D5-152). */
	save_preference: boolean,
};

export type SubmitFocusRunRequest = {
	focus_id: string,
	user_input: string,
	user_id: string,
	persona_id: string,
	key_hex: string,
	topic_id: string | null,
	/**
	 *  entity_facts.id values the user approved via the pre-Focus-start
	 *  cross-Persona confirmation flow (decisions.id=546, decisions.id=639,
	 *  items.id=27) -- obtained by calling
	 *  commands::consent::get_pending_cross_persona_confirmations() before
	 *  this command. Any cross_persona_export=true fact whose id is absent
	 *  here is omitted from context, not blocked (declined-or-unasked case).
	 *  Empty vec is valid -- most runs have no pending cross-Persona facts.
	 */
	confirmed_cross_persona_fact_ids: string[],
};

export type SubmitFocusRunResponse = {
	run_id: string,
};

/**
 *  items.id=92 -- the user's proceed/cancel answer to a FrictionGateDetail
 *  the frontend received from a blocked update_focus_settings call.
 * 
 *  original_request carries the FULL originally-attempted settings change
 *  (not just the two gate-relevant fields) so that on decision="proceed"
 *  this command can apply the whole update in one call -- a real settings
 *  screen may bundle a gate-tripping field change together with
 *  non-gate-tripping ones (e.g. privacy_tier loosening alongside a
 *  context_flow change), and both must land together, not in two separate
 *  writes the frontend has to sequence itself.
 */
export type SubmitFrictionGateDecisionRequest = {
	/**  "proceed" | "cancel" */
	decision: string,
	original_request: UpdateFocusSettingsRequest,
};

/**
 *  Non-secret Tier 2 configuration state -- never carries the credential
 *  itself. `configured` is true iff an active user-global tier2 key exists
 *  for `provider`.
 */
export type Tier2Config = {
	provider: string,
	configured: boolean,
	expires_at: string | null,
};

/**
 *  Selector-screen-facing provider summary. `lane` mirrors
 *  `provider_store::ProviderTier`'s own serde rendering ("tier2"/"tier3")
 *  and the frontend's `ProviderLane` string type (tier3AccessConfig.ts)
 *  verbatim -- no further transformation needed on the TypeScript side.
 */
export type Tier3ProviderSummary = {
	id: string,
	display_name: string,
	lane: string,
};

export type TopicInfo = {
	id: string,
	focus_id: string,
	lifecycle_state: string,
	display_name: string,
	updated_at: string,
};

export type UpdateFocusSettingsRequest = {
	persona_id: string,
	focus_id: string,
	context_flow: string | null,
	library_visibility: string | null,
	privacy_tier: number | null,
	max_permitted_tier: number | null,
	focus_profile: string | null,
};

export type UpdatePersonalFieldRequest = {
	persona_id: string,
	user_id: string,
	key_hex: string,
	field_name: string,
	value: string,
	/**
	 *  Sensitivity of the field value. Defaults to "personal" if omitted.
	 *  Validation (general/personal/medical/financial) is enforced by the store.
	 */
	sensitivity: string | null,
};

export type UpdateTopicStateRequest = {
	topic_id: string,
	user_id: string,
	persona_id: string,
	key_hex: string,
	state: string,
};

/**
 *  IPC projection of voice profile. The store may contain additional attributes
 *  beyond these three; they are intentionally dropped at the IPC boundary.
 *  The IPC surface specifies tone, formality, length_preference only.
 */
export type VoiceProfileInfo = {
	tone: string,
	formality: string,
	length_preference: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

