// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	submitFocusRun: (request: SubmitFocusRunRequest) => typedError<SubmitFocusRunResponse, string>(__TAURI_INVOKE("submit_focus_run", { request })),
	getRunOutput: (runId: string, userId: string, personaId: string, keyHex: string) => typedError<GetRunOutputResponse, string>(__TAURI_INVOKE("get_run_output", { runId, userId, personaId, keyHex })),
	cancelRun: (runId: string, userId: string, personaId: string, keyHex: string) => typedError<null, string>(__TAURI_INVOKE("cancel_run", { runId, userId, personaId, keyHex })),
	/**
	 *  Resume a paused focus run.
	 * 
	 *  awaiting_extract_confirm routing:
	 *    1. Crash-recovery replay: rows with status='confirmed' AND persisted_at IS NULL
	 *       -> replay persist_confirmed_field() + set_persisted_at() using persisted
	 *       sensitivity (never recomputed -- see load_unrecovered_rows() doc).
	 *    2. If pending > 0: re-emit extract_confirm_request push event and return.
	 *    3. If pending == 0: all candidates decided. output() is called by
	 *       submit_extract_confirm once the user submits decisions -- not from here.
	 *       Full snapshot replay for this path is deferred post-Release-1.
	 * 
	 *  Other statuses: returns not_implemented (stub behaviour unchanged).
	 */
	resumeRun: (request: ResumeRunRequest) => typedError<string, string>(__TAURI_INVOKE("resume_run", { request })),
	submitConsentDecision: (request: SubmitConsentDecisionRequest) => typedError<null, string>(__TAURI_INVOKE("submit_consent_decision", { request })),
	submitFloorConsentDecision: (request: SubmitFloorConsentDecisionRequest) => typedError<null, string>(__TAURI_INVOKE("submit_floor_consent_decision", { request })),
	submitElementConsentDecision: (request: SubmitElementConsentDecisionRequest) => typedError<null, string>(__TAURI_INVOKE("submit_element_consent_decision", { request })),
	/**
	 *  items.id=92 -- process the user's proceed/cancel answer to a friction-gate
	 *  block returned by commands::persona::update_focus_settings.
	 * 
	 *  On "cancel": records the decision only. No settings change is applied --
	 *  the Focus keeps its prior settings exactly as they were.
	 * 
	 *  On "proceed": records the decision, THEN applies original_request via
	 *  focus_settings_store::update_focus_settings directly (NOT by calling
	 *  commands::persona::update_focus_settings again, which would immediately
	 *  re-trip the same gate check this command exists to get past). Both
	 *  writes happen in this one call -- the frontend does not make a second
	 *  settings-update request itself.
	 * 
	 *  Re-validates original_request's tier bounds before applying, mirroring
	 *  update_focus_settings's own guard -- this command is a second entry
	 *  point into the same mutation and must not skip a check the first entry
	 *  point enforces, even though the friction-gate values themselves were
	 *  already validated once when update_focus_settings first computed them.
	 */
	submitFrictionGateDecision: (request: SubmitFrictionGateDecisionRequest) => typedError<{
	focus_id: string,
	focus_profile: string,
	context_flow: string,
	library_visibility: string,
	privacy_tier: number,
	max_permitted_tier: number,
	updated_at: string,
} | null, string>(__TAURI_INVOKE("submit_friction_gate_decision", { request })),
	/**
	 *  Process user decisions for extract-and-confirm candidates (item 20).
	 * 
	 *  Validation: confirmed==true with confirmed_value==None rejects entire call
	 *  before any DB mutation (IPC contract violation).
	 * 
	 *  Processing set: pending candidates + confirmed-but-unpersisted (crash-recovery
	 *  targets). Both are included so retries can complete interrupted work.
	 * 
	 *  Write sequence per confirmed pending candidate:
	 *    1. get_candidate_fields()    -> read field_name + sensitivity from outputs.db
	 *    2. persist_confirmed_field() -> COMMIT personal.db (idempotent upsert)
	 *    3. mark_candidate_decided()  -> COMMIT outputs.db (sets confirmed_at)
	 *    4. set_persisted_at()        -> COMMIT outputs.db
	 * 
	 *  Ordering rationale: personal.db write first so that on retry, if step 3/4
	 *  failed, we re-attempt an idempotent upsert rather than leaving candidate
	 *  marked decided with no persisted field.
	 * 
	 *  After all decisions: verify no confirmed-but-unpersisted rows remain,
	 *  then set focus_runs.status='complete' and emit run_status_update.
	 */
	submitExtractConfirm: (request: SubmitExtractConfirmRequest) => typedError<null, string>(__TAURI_INVOKE("submit_extract_confirm", { request })),
	/**
	 *  Pre-Focus-start query: which cross_persona_export=true entity_facts rows
	 *  exist for this persona and require per-session confirmation before a
	 *  Focus run may include them (decisions.id=546, decisions.id=639, items.id=27).
	 * 
	 *  Called by the frontend BEFORE FocusRun::new() is constructed. Read-only --
	 *  this command does not write a decision anywhere. The frontend shows a
	 *  confirmation UI for the returned facts, then passes the fact_ids the user
	 *  approved into SubmitFocusRunRequest.confirmed_cross_persona_fact_ids.
	 *  Facts not included there are treated as declined by
	 *  apply_entity_fact_provenance_check() -- omitted from context, not a
	 *  hard block (Jason, this session: declining one fact should not block
	 *  the whole run).
	 */
	getPendingCrossPersonaConfirmations: (request: GetPendingCrossPersonaConfirmationsRequest) => typedError<PendingCrossPersonaFact[], string>(__TAURI_INVOKE("get_pending_cross_persona_confirmations", { request })),
	getOnboardingFocusSuggestions: (personas: string[]) => typedError<NotImplementedPlaceholder, string>(__TAURI_INVOKE("get_onboarding_focus_suggestions", { personas })),
	submitOnboardingPersonaSelection: (personas: string[]) => typedError<string[], string>(__TAURI_INVOKE("submit_onboarding_persona_selection", { personas })),
	submitOnboardingFocusSelection: (focusSelections: NotImplementedPlaceholder[]) => typedError<string[], string>(__TAURI_INVOKE("submit_onboarding_focus_selection", { focusSelections })),
	listPersonas: (userId: string) => typedError<PersonaInfo[], string>(__TAURI_INVOKE("list_personas", { userId })),
	createPersona: (request: CreatePersonaRequest) => typedError<CreatePersonaResponse, string>(__TAURI_INVOKE("create_persona", { request })),
	listFocuses: (personaId: string) => typedError<FocusInfo[], string>(__TAURI_INVOKE("list_focuses", { personaId })),
	/**
	 *  get_focus_settings takes both persona_id and focus_id — the store key is
	 *  composite. The IPC spec lists focus_id only (higher-level abstraction).
	 */
	getFocusSettings: (personaId: string, focusId: string) => typedError<FocusInfo, string>(__TAURI_INVOKE("get_focus_settings", { personaId, focusId })),
	/**
	 *  Applies a Focus settings change directly, UNLESS the change would loosen
	 *  privacy_tier or move focus_profile to 'protected' -- in which case this
	 *  returns Err(json-serialized FrictionGateDetail) instead of applying
	 *  anything, and the frontend must route the user through
	 *  commands::consent::submit_friction_gate_decision to either apply the
	 *  change (decision="proceed") or drop it (decision="cancel"). See module
	 *  header for the full flow and the tier-direction note.
	 * 
	 *  The error string is JSON (FrictionGateDetail serialized), not a plain
	 *  message -- distinguishable from every other error this command can
	 *  return (validation failures, not_found) by attempting a JSON parse.
	 *  A frontend that doesn't parse it still gets a readable-enough string,
	 *  but the structured shape is what submit_friction_gate_decision expects
	 *  to be built from.
	 */
	updateFocusSettings: (request: UpdateFocusSettingsRequest) => typedError<FocusInfo, string>(__TAURI_INVOKE("update_focus_settings", { request })),
	getActiveBoard: (userId: string, personaId: string, keyHex: string) => typedError<ActiveBoardResponse, string>(__TAURI_INVOKE("get_active_board", { userId, personaId, keyHex })),
	getTopicList: (focusId: string, userId: string, personaId: string, keyHex: string) => typedError<TopicInfo[], string>(__TAURI_INVOKE("get_topic_list", { focusId, userId, personaId, keyHex })),
	updateTopicState: (request: UpdateTopicStateRequest) => typedError<null, string>(__TAURI_INVOKE("update_topic_state", { request })),
	getPersonalFields: (personaId: string, userId: string, keyHex: string) => typedError<PersonalFieldInfo[], string>(__TAURI_INVOKE("get_personal_fields", { personaId, userId, keyHex })),
	updatePersonalField: (request: UpdatePersonalFieldRequest) => typedError<PersonalFieldInfo, string>(__TAURI_INVOKE("update_personal_field", { request })),
	getVoiceProfile: (personaId: string, userId: string, keyHex: string) => typedError<VoiceProfileInfo, string>(__TAURI_INVOKE("get_voice_profile", { personaId, userId, keyHex })),
	/**
	 *  Lists active outputs, optionally filtered by focus_id, topic_id, and/or
	 *  output_type. Wired to output_store::list_outputs() (items.id=91, part 1).
	 * 
	 *  Does NOT enforce Focus profile visibility rules (Open/Organized/
	 *  Protected) -- that filtering layer is a separate, not-yet-built gap,
	 *  split to items.id=175 (post-Release 1). See module header.
	 */
	listOutputs: (userId: string, personaId: string, keyHex: string, focusId: string | null, topicId: string | null, outputType: string | null) => typedError<OutputInfo[], string>(__TAURI_INVOKE("list_outputs", { userId, personaId, keyHex, focusId, topicId, outputType })),
	getOutput: (outputId: string, userId: string, personaId: string, keyHex: string) => typedError<OutputInfo, string>(__TAURI_INVOKE("get_output", { outputId, userId, personaId, keyHex })),
	/**
	 *  Deletes an output (items.id=91, part 2, complete 2026-07-26). Soft-delete
	 *  only -- content is zeroed and status set to 'deleted'; the row is never
	 *  hard-deleted (architecture Section 3.4, output_store::delete_output).
	 * 
	 *  deep_purge: accepted for command-contract stability but NOT implemented.
	 *  Passing Some(true) returns Err("deep_purge_not_implemented"). See
	 *  output_store::delete_output's doc comment for why this is deliberately
	 *  out of scope for R1.
	 */
	deleteOutput: (outputId: string, userId: string, personaId: string, keyHex: string, deepPurge: boolean | null) => typedError<null, string>(__TAURI_INVOKE("delete_output", { outputId, userId, personaId, keyHex, deepPurge })),
	getFocusBuilderSession: (focusId: string | null) => typedError<NotImplementedPlaceholder, string>(__TAURI_INVOKE("get_focus_builder_session", { focusId })),
	submitFocusBuilderStep: (sessionId: string, input: NotImplementedPlaceholder) => typedError<NotImplementedPlaceholder, string>(__TAURI_INVOKE("submit_focus_builder_step", { sessionId, input })),
	/**
	 *  Report configuration state for a Tier 2 provider. Returns
	 *  configured=false (not an error) when no key is set yet -- an
	 *  unconfigured provider is a normal, expected state, not a failure.
	 */
	getTier2Config: (provider: string) => typedError<Tier2Config, string>(__TAURI_INVOKE("get_tier2_config", { provider })),
	/**  Set (or replace) the credential for a Tier 2 provider, user-global scope. */
	setTier2Provider: (provider: string, apiKey: string) => typedError<null, string>(__TAURI_INVOKE("set_tier2_provider", { provider, apiKey })),
	dismissNotification: (notificationId: string) => typedError<null, string>(__TAURI_INVOKE("dismiss_notification", { notificationId })),
	login: (displayName: string, password: string) => typedError<null, string>(__TAURI_INVOKE("login", { displayName, password })),
	logout: () => typedError<null, string>(__TAURI_INVOKE("logout")),
	getRecoveryKeyDisplay: () => typedError<NotImplementedPlaceholder, string>(__TAURI_INVOKE("get_recovery_key_display")),
	getHealth: () => typedError<HealthResponse, string>(__TAURI_INVOKE("get_health")),
	getCapabilityProfile: () => typedError<CapabilityProfileResponse, string>(__TAURI_INVOKE("get_capability_profile")),
};

/* Types */
export type ActiveBoardResponse = {
	topics: TopicInfo[],
	/**
	 *  Placeholder -- Daily Brief not yet implemented. Will become a typed
	 *  struct when wired; serialized as JSON string in the interim.
	 */
	daily_brief: string | null,
	/**  Placeholder -- Quick Launch Dock not yet implemented. */
	quick_launch: string[],
};

export type CapabilityProfileResponse = {
	installed_models: string[],
	/**
	 *  Release 1: "pending" | "unavailable" only.
	 *  "complete" requires evaluation/scores DB port (post-Release 1).
	 *  STUB: recommended_routing omitted until scores DB is ported.
	 */
	benchmark_status: string,
};

export type CreatePersonaRequest = {
	user_id: string,
	name: string,
	persona_type: string | null,
};

export type CreatePersonaResponse = {
	persona_id: string,
};

/**  IPC gap: missing dormancy_state, last_used (post-Release 1). */
export type FocusInfo = {
	focus_id: string,
	focus_profile: string,
	context_flow: string,
	library_visibility: string,
	privacy_tier: number,
	max_permitted_tier: number,
	updated_at: string,
};

export type GetPendingCrossPersonaConfirmationsRequest = {
	user_id: string,
	persona_id: string,
	key_hex: string,
};

export type GetRunOutputResponse = {
	content: string,
	output_type: string,
	sensitivity: string,
};

export type HealthResponse = {
	ollama: ProviderHealth,
	/**
	 *  "system" | "sidecar" | "unavailable".
	 *  Set during app setup by OllamaSidecar::ensure_available().
	 *  "unavailable" is returned during the brief startup detection window.
	 */
	ollama_source: string,
	/**  Always false until integration_keys store is ported (Group 9 stub). */
	tier2_configured: boolean,
};

/**
 *  Placeholder request/response shape for commands that are declared but not
 *  yet built.
 * 
 *  Why this exists (items.id=27): five stub commands
 *  (onboarding::get_onboarding_focus_suggestions,
 *  onboarding::submit_onboarding_focus_selection,
 *  focus_builder::get_focus_builder_session,
 *  focus_builder::submit_focus_builder_step, tier2::get_tier2_config)
 *  previously used serde_json::Value as an argument or return type.
 *  serde_json::Value is self-referential (Array(Vec<Value>),
 *  Object(Map<String, Value>)), and specta's TypeScript exporter recurses
 *  through it without terminating -- confirmed empirically: excluding exactly
 *  those five commands makes the export succeed, and a 64 MB stack does not
 *  help.
 * 
 *  These commands all return Err("not_implemented") today and have no designed
 *  payload shape, so serde_json::Value was a placeholder rather than a decided
 *  contract. This type says that explicitly instead. Each of the five should
 *  be given its real request/response struct when its feature is designed --
 *  this is deliberately not a contract to build against.
 * 
 *  UPDATE (items.id=185, 2026-08-02): tier2::get_tier2_config now has a real
 *  return type (commands::tier2::Tier2Config) and no longer uses this
 *  placeholder -- four of the original five remain unbuilt.
 */
export type NotImplementedPlaceholder = Record<string, never>;

export type OutputInfo = {
	id: string,
	focus_run_id: string,
	output_type: string,
	content: string,
	sensitivity: string,
	status: string,
	created_at: string,
};

/**
 *  IPC-safe projection of an entity_facts row pending cross-Persona
 *  confirmation (decisions.id=546, decisions.id=639, items.id=27).
 *  field_value is intentionally absent -- mirrors PersonalFieldInfo's
 *  no-raw-values convention in commands/personal.rs.
 */
export type PendingCrossPersonaFact = {
	/**
	 *  entity_facts.id -- pass this back in
	 *  SubmitFocusRunRequest.confirmed_cross_persona_fact_ids for any fact
	 *  the user approves.
	 */
	fact_id: string,
	entity_id: string | null,
	field_name: string,
	sensitivity: string,
	/**
	 *  The Persona instance this fact originated in (decisions.id=546).
	 *  Always Some for a row with cross_persona_export=true -- the DB CHECK
	 *  constraint on entity_facts (personal_001.sql) guarantees this.
	 */
	origin_persona_id: string | null,
};

/**  IPC gap: missing color, focus_count, privacy defaults (post-Release 1). */
export type PersonaInfo = {
	id: string,
	display_name: string,
	persona_type: string,
	created_at: string,
};

/**  IPC-safe projection of PersonalField. field_value is intentionally absent. */
export type PersonalFieldInfo = {
	field_name: string,
	sensitivity: string,
	/**  Abstracted display value for Tier 2 routing contexts. */
	abstraction_tier2: string,
	/**  Abstracted display value for Tier 3 routing contexts. */
	abstraction_tier3: string,
};

export type ProviderHealth = {
	provider: string,
	status: ProviderStatus,
	/**  ISO 8601 UTC string. */
	checked_at: string,
	error: string | null,
	available_models?: string[],
};

export type ProviderStatus = "available" | "degraded" | "unavailable";

export type ResumeRunRequest = {
	run_id: string,
	user_id: string,
	persona_id: string,
	key_hex: string,
};

export type SubmitConsentDecisionRequest = {
	run_id: string,
	user_id: string,
	persona_id: string,
	key_hex: string,
	/**  "approved" | "declined" */
	decision: string,
};

export type SubmitElementConsentDecisionRequest = {
	run_id: string,
	user_id: string,
	persona_id: string,
	key_hex: string,
	/**
	 *  JSON-serialized Vec<ElementDecision> produced by the frontend.
	 *  Expected shape per element:
	 *    { "span_id": string, "decision": "generalize"|"keep_private"|"release_original",
	 *      "suggestion_text": string|null, "user_modified_text": string|null }
	 *  The command layer does not deserialize this -- it is passed through to
	 *  write_element_consent_decisions() as-is (D6-362 IPC boundary rule).
	 */
	decisions_json: string,
};

export type SubmitExtractConfirmRequest = {
	run_id: string,
	user_id: string,
	persona_id: string,
	key_hex: string,
	/**
	 *  JSON-serialized Vec<ExtractConfirmDecision>.
	 *  Shape per element:
	 *    { "candidate_id": i64, "confirmed": bool,
	 *      "extracted_value": string, "confirmed_value": string|null }
	 *  confirmed_value must be non-null when confirmed==true.
	 */
	decisions_json: string,
};

export type SubmitFloorConsentDecisionRequest = {
	run_id: string,
	user_id: string,
	persona_id: string,
	key_hex: string,
	abstraction_tier: number,
	/**  "proceed" | "cancel" */
	decision: string,
	/**  If true, saves as standing floor consent preference (D5-152). */
	save_preference: boolean,
};

export type SubmitFocusRunRequest = {
	focus_id: string,
	user_input: string,
	user_id: string,
	persona_id: string,
	key_hex: string,
	topic_id: string | null,
	/**
	 *  entity_facts.id values the user approved via the pre-Focus-start
	 *  cross-Persona confirmation flow (decisions.id=546, decisions.id=639,
	 *  items.id=27) -- obtained by calling
	 *  commands::consent::get_pending_cross_persona_confirmations() before
	 *  this command. Any cross_persona_export=true fact whose id is absent
	 *  here is omitted from context, not blocked (declined-or-unasked case).
	 *  Empty vec is valid -- most runs have no pending cross-Persona facts.
	 */
	confirmed_cross_persona_fact_ids: string[],
};

export type SubmitFocusRunResponse = {
	run_id: string,
};

/**
 *  items.id=92 -- the user's proceed/cancel answer to a FrictionGateDetail
 *  the frontend received from a blocked update_focus_settings call.
 * 
 *  original_request carries the FULL originally-attempted settings change
 *  (not just the two gate-relevant fields) so that on decision="proceed"
 *  this command can apply the whole update in one call -- a real settings
 *  screen may bundle a gate-tripping field change together with
 *  non-gate-tripping ones (e.g. privacy_tier loosening alongside a
 *  context_flow change), and both must land together, not in two separate
 *  writes the frontend has to sequence itself.
 */
export type SubmitFrictionGateDecisionRequest = {
	/**  "proceed" | "cancel" */
	decision: string,
	original_request: UpdateFocusSettingsRequest,
};

/**
 *  Non-secret Tier 2 configuration state -- never carries the credential
 *  itself. `configured` is true iff an active user-global tier2 key exists
 *  for `provider`.
 */
export type Tier2Config = {
	provider: string,
	configured: boolean,
	expires_at: string | null,
};

export type TopicInfo = {
	id: string,
	focus_id: string,
	lifecycle_state: string,
	display_name: string,
	updated_at: string,
};

export type UpdateFocusSettingsRequest = {
	persona_id: string,
	focus_id: string,
	context_flow: string | null,
	library_visibility: string | null,
	privacy_tier: number | null,
	max_permitted_tier: number | null,
	focus_profile: string | null,
};

export type UpdatePersonalFieldRequest = {
	persona_id: string,
	user_id: string,
	key_hex: string,
	field_name: string,
	value: string,
	/**
	 *  Sensitivity of the field value. Defaults to "personal" if omitted.
	 *  Validation (general/personal/medical/financial) is enforced by the store.
	 */
	sensitivity: string | null,
};

export type UpdateTopicStateRequest = {
	topic_id: string,
	user_id: string,
	persona_id: string,
	key_hex: string,
	state: string,
};

/**
 *  IPC projection of voice profile. The store may contain additional attributes
 *  beyond these three; they are intentionally dropped at the IPC boundary.
 *  The IPC surface specifies tone, formality, length_preference only.
 */
export type VoiceProfileInfo = {
	tone: string,
	formality: string,
	length_preference: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

