// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  TEMPORARY dev-only test scaffolding (items.id=329, DIAG_329). Seeds a
	 *  synthetic "drafted" assistant message directly, skipping real Focus-run
	 *  execution/model generation, so a debug build can jump straight into
	 *  request_tier3_gate3_review without the several-seconds-per-iteration
	 *  manual type-a-message/wait-for-the-model dance. The seeded row still goes
	 *  through the REAL request_tier3_gate3_review -> gate3() path unmodified --
	 *  this only fabricates the drafted input Gate3 reviews, not Gate3's own
	 *  approve/deny decision or the tier-ceiling check ahead of it.
	 * 
	 *  focus_run_id is a fresh synthetic id, not a real focus_runs.id -- both
	 *  places that store it (messages.focus_run_id, disclosure_log.focus_run_id)
	 *  are plain TEXT columns with no FK, and live in different SQLite files
	 *  than focus_runs anyway, so this is safe (confirmed 2026-08-28).
	 * 
	 *  #[cfg(debug_assertions)]: compiled only into debug builds -- absent
	 *  entirely from a release binary, not just unreachable. See ipc.rs's
	 *  specta_builder for the matching debug-only command registration; both
	 *  halves must be removed together once items.id=329's Tier 3 pane work no
	 *  longer needs fast iteration.
	 */
	devSeedTier3DraftMessage: (userId: string, personaId: string, contextKey: string) => typedError<string, string>(__TAURI_INVOKE("dev_seed_tier3_draft_message", { userId, personaId, contextKey })),
	/**
	 *  TEMPORARY dev-only bypass for the "Dev: force Tier 3 escalation" button
	 *  (items.id=356, Tier3AccessPane.tsx's handleDevForceTier3). Skips gate3()
	 *  entirely -- unlike dev_seed_tier3_draft_message above (which fabricates
	 *  only the drafted INPUT gate3 reviews, still routing through the real
	 *  gate), this command skips the real gate decision itself.
	 * 
	 *  Why: gate3's own zero-spans-forced-High branch (D6-362/decisions.id=405,
	 *  see gate3.rs's header comment) reliably fires for this synthetic
	 *  dev-seeded message and surfaces a Privacy Guardian modal with nothing in
	 *  it to review -- a real, separately-tracked UX gap (items.id=356) that
	 *  this command works around for dev testing, not fixes. Whether that
	 *  empty-modal branch should exist at all, and what it should show instead,
	 *  is deferred design work -- gate3.rs is untouched by this item. Real user
	 *  messages never call this command; they still go through the unmodified
	 *  request_tier3_gate3_review -> gate3() path above, unchanged.
	 * 
	 *  Marks the message approved directly (mirroring
	 *  request_tier3_gate3_review's own gate3_review_status transition on its
	 *  approved branch) without ever constructing a PrivacyGateway or calling
	 *  gateway.gate3().
	 * 
	 *  #[cfg(debug_assertions)]: compiled only into debug builds, same
	 *  discipline as dev_seed_tier3_draft_message -- see ipc.rs's specta_builder
	 *  for the matching debug-only registration; both halves must be removed
	 *  together once items.id=356's Privacy Guardian empty-modal design work
	 *  lands and this workaround is no longer needed.
	 */
	devBypassTier3Gate3Review: (request: RequestTier3Gate3ReviewRequest) => typedError<Gate3ReviewResult, string>(__TAURI_INVOKE("dev_bypass_tier3_gate3_review", { request })),
	submitFocusRun: (request: SubmitFocusRunRequest) => typedError<SubmitFocusRunResponse, string>(__TAURI_INVOKE("submit_focus_run", { request })),
	getRunOutput: (runId: string, userId: string, personaId: string) => typedError<GetRunOutputResponse, string>(__TAURI_INVOKE("get_run_output", { runId, userId, personaId })),
	cancelRun: (runId: string, userId: string, personaId: string) => typedError<null, string>(__TAURI_INVOKE("cancel_run", { runId, userId, personaId })),
	/**
	 *  Resume a paused focus run.
	 * 
	 *  Routes by focus_runs.status (schema/outputs_001.sql CHECK — the full set
	 *  is 'initializing','running','paused','awaiting_user','awaiting_feedback',
	 *  'awaiting_extract_confirm','complete','cancelled','failed').
	 * 
	 *  awaiting_extract_confirm routing:
	 *    1. Crash-recovery replay: rows with status='confirmed' AND persisted_at IS NULL
	 *       -> replay persist_confirmed_field() + set_persisted_at() using persisted
	 *       sensitivity (never recomputed -- see load_unrecovered_rows() doc).
	 *    2. If pending > 0: re-emit extract_confirm_request push event and return.
	 *    3. If pending == 0: all candidates decided. output() is called by
	 *       submit_extract_confirm once the user submits decisions -- not from here.
	 *       Full snapshot replay for this path is deferred post-Release-1.
	 * 
	 *  complete/cancelled/failed: terminal -- there is nothing to resume, so this
	 *  returns a distinct "already finished" error rather than not_implemented,
	 *  which would incorrectly imply resume itself is the missing piece.
	 * 
	 *  awaiting_feedback: Phase 5 OUTPUT already ran and saved content (see
	 *  lifecycle.rs output()) -- Phase 6 FEEDBACK is explicitly out of scope of
	 *  the FocusRun module (lifecycle.rs module header, "out of scope for this
	 *  module (async paste-back)"). Nothing is pending execution; the caller
	 *  should fetch the already-produced output via get_run_output instead.
	 * 
	 *  awaiting_user, paused, running, initializing: genuinely not_implemented
	 *  (unchanged stub behaviour). All four are blocked on the same structural
	 *  gap, not a missing switch statement: FocusRun::new() requires
	 *  `user_input`, and every step's prompt render threads it through
	 *  StepContext (lifecycle.rs execute_step()) -- but user_input is never
	 *  persisted anywhere (not on focus_runs, not in focus_run_snapshots). There
	 *  is currently no way to reconstruct a live FocusRun to re-enter execute()
	 *  for any of these four statuses without first adding somewhere to store
	 *  it, which is a schema change, not a resume_run fix. See each match arm
	 *  below for the state-specific detail on top of that shared blocker.
	 */
	resumeRun: (request: ResumeRunRequest) => typedError<string, string>(__TAURI_INVOKE("resume_run", { request })),
	submitConsentDecision: (request: SubmitConsentDecisionRequest) => typedError<null, string>(__TAURI_INVOKE("submit_consent_decision", { request })),
	submitFloorConsentDecision: (request: SubmitFloorConsentDecisionRequest) => typedError<null, string>(__TAURI_INVOKE("submit_floor_consent_decision", { request })),
	submitElementConsentDecision: (request: SubmitElementConsentDecisionRequest) => typedError<null, string>(__TAURI_INVOKE("submit_element_consent_decision", { request })),
	/**
	 *  items.id=92 -- process the user's proceed/cancel answer to a friction-gate
	 *  block returned by commands::persona::update_focus_settings.
	 * 
	 *  On "cancel": records the decision only. No settings change is applied --
	 *  the Focus keeps its prior settings exactly as they were.
	 * 
	 *  On "proceed": records the decision, THEN applies original_request via
	 *  focus_settings_store::update_focus_settings directly (NOT by calling
	 *  commands::persona::update_focus_settings again, which would immediately
	 *  re-trip the same gate check this command exists to get past). Both
	 *  writes happen in this one call -- the frontend does not make a second
	 *  settings-update request itself.
	 * 
	 *  Re-validates original_request's tier bounds before applying, mirroring
	 *  update_focus_settings's own guard -- this command is a second entry
	 *  point into the same mutation and must not skip a check the first entry
	 *  point enforces, even though the friction-gate values themselves were
	 *  already validated once when update_focus_settings first computed them.
	 */
	submitFrictionGateDecision: (request: SubmitFrictionGateDecisionRequest) => typedError<{
	focus_id: string,
	focus_profile: string,
	context_flow: string,
	library_visibility: string,
	privacy_tier: number,
	max_permitted_tier: ExternalAccess,
	updated_at: string,
	/**
	 *  Most recent focus_runs.started_at for this Focus (outputs.db), or
	 *  None if it has never run or outputs.db isn't reachable with the
	 *  supplied key_hex. NOT the same as updated_at (settings-edit time).
	 */
	last_used: string | null,
} | null, string>(__TAURI_INVOKE("submit_friction_gate_decision", { request })),
	/**
	 *  Process user decisions for extract-and-confirm candidates (item 20).
	 * 
	 *  Validation: confirmed==true with confirmed_value==None rejects entire call
	 *  before any DB mutation (IPC contract violation).
	 * 
	 *  Processing set: pending candidates + confirmed-but-unpersisted (crash-recovery
	 *  targets). Both are included so retries can complete interrupted work.
	 * 
	 *  Write sequence per confirmed pending candidate:
	 *    1. get_candidate_fields()    -> read field_name + sensitivity from outputs.db
	 *    2. persist_confirmed_field() -> COMMIT personal.db (idempotent upsert)
	 *    3. mark_candidate_decided()  -> COMMIT outputs.db (sets confirmed_at)
	 *    4. set_persisted_at()        -> COMMIT outputs.db
	 * 
	 *  Ordering rationale: personal.db write first so that on retry, if step 3/4
	 *  failed, we re-attempt an idempotent upsert rather than leaving candidate
	 *  marked decided with no persisted field.
	 * 
	 *  After all decisions: verify no confirmed-but-unpersisted rows remain,
	 *  then set focus_runs.status='complete' and emit run_status_update.
	 */
	submitExtractConfirm: (request: SubmitExtractConfirmRequest) => typedError<null, string>(__TAURI_INVOKE("submit_extract_confirm", { request })),
	/**
	 *  Pre-Focus-start query: which cross_persona_export=true entity_facts rows
	 *  exist for this persona and require per-session confirmation before a
	 *  Focus run may include them (decisions.id=546, decisions.id=639, items.id=27).
	 * 
	 *  Called by the frontend BEFORE FocusRun::new() is constructed. Read-only --
	 *  this command does not write a decision anywhere. The frontend shows a
	 *  confirmation UI for the returned facts, then passes the fact_ids the user
	 *  approved into SubmitFocusRunRequest.confirmed_cross_persona_fact_ids.
	 *  Facts not included there are treated as declined by
	 *  apply_entity_fact_provenance_check() -- omitted from context, not a
	 *  hard block (Jason, this session: declining one fact should not block
	 *  the whole run).
	 */
	getPendingCrossPersonaConfirmations: (request: GetPendingCrossPersonaConfirmationsRequest) => typedError<PendingCrossPersonaFact[], string>(__TAURI_INVOKE("get_pending_cross_persona_confirmations", { request })),
	/**
	 *  PG_GATE_3, invoked against a drafted Tier-3-starter message
	 *  (messages.gate3_review_status = 'drafted', written by
	 *  commands::messages::send_message's gate3_track=true path). Completes
	 *  items.id=233's remaining stub -- see the former "NO OUTBOUND PRIVACY
	 *  GUARDIAN REVIEW HAPPENS" marker this command replaces in
	 *  Tier3AccessPane.tsx for the investigation that scoped it.
	 * 
	 *  Unlike every other command in this file, this one *triggers* gate3()
	 *  rather than *responding to* an already-fired one -- gate3()'s only prior
	 *  call site was conductor/executor.rs's own step-execution loop, with no
	 *  StepContext/PersonalTrack available here.
	 * 
	 *  This call site reviews arbitrary message content drafted ahead of Tier 3
	 *  access, via any entry path (direct chat, escalation, or a Focus-run
	 *  handoff) -- it is NOT specific to Quick-Ask-Focus-generated content, and
	 *  makes no claim that no personal fields ever flow through it. quick-ask.focus's
	 *  step id and display_name are reused below purely as a synthetic label for
	 *  disclosure_log/audit purposes, not as a claim about the reviewed
	 *  content's structure.
	 * 
	 *  Parameter sourcing:
	 *    - target_tier=3: this flow only exists ahead of Tier 3 access.
	 *    - execution_tier=1, content_sensitivity_severity=1: no PersonalTrack is
	 *      available at this call site to compute a real severity, so this is a
	 *      fixed placeholder, not a real assessment.
	 *    - step_id="draft", focus_name="Quick Ask": quick-ask.focus's own step
	 *      id and display_name, borrowed as a synthetic label only -- see above.
	 *    - severity_authoritative=false (items.id=458, corrected scope of the
	 *      earlier items.id=799): content_sensitivity_severity=1 being a
	 *      placeholder means a live destination_risk alone must not force
	 *      gate3's High-tier consent gate on zero PF spans here -- that produced
	 *      an empty, uninformative interrupt. See
	 *      zero_spans_safe_to_auto_approve's own doc comment in gate3.rs.
	 *    - space_max_permitted_tier: a real per-Persona focus_settings lookup,
	 *      never a constant -- missing row is a hard Err, mirroring AUTHORIZE's
	 *      own assertion (lifecycle.rs).
	 * 
	 *  Uses SqliteDisclosureLogger (FocusRun's own default logger), not
	 *  NoopLogger/TestLogger, so the write-before-surface disclosure_log entry
	 *  gate3() writes is real, not discarded.
	 * 
	 *  gate3_review_status transition: 'pending_consent' -> 'pending-review';
	 *  'approved' (PF found nothing needing review) -> 'approved'. On
	 *  'blocked'/'timeout' the row is left at 'drafted' -- gate3_review_status's
	 *  CHECK constraint has no "blocked" state, and leaving it at 'drafted'
	 *  keeps the row retry-able rather than overloading 'withheld' (a status
	 *  meaning the user declined, not that gate3 itself refused).
	 */
	requestTier3Gate3Review: (request: RequestTier3Gate3ReviewRequest) => typedError<Gate3ReviewResult, string>(__TAURI_INVOKE("request_tier3_gate3_review", { request })),
	/**
	 *  Records the user's resolution of a Privacy Guardian consent review
	 *  (pending-review -> approved | withheld). Separate from
	 *  submit_element_consent_decision: that command writes the per-span audit
	 *  record to outputs.db's consent_decisions (keyed by run_id); this one
	 *  transitions messages.db's gate3_review_status (keyed by message_id) --
	 *  two different persistence targets. The frontend calls both after the
	 *  user resolves the Privacy Guardian modal (submit_element_consent_decision
	 *  first, then this).
	 */
	resolveTier3Gate3Review: (request: ResolveTier3Gate3ReviewRequest) => typedError<null, string>(__TAURI_INVOKE("resolve_tier3_gate3_review", { request })),
	/**
	 *  items.id=406 (decisions.id=755) -- the provider-selection re-check
	 *  trigger. Fires when the user activates a rail provider not covered by
	 *  the message's original copy-time review (Tier3AccessPane.tsx, provider
	 *  row activation -- a QR-owned UI event, unlike paste inside an embedded
	 *  CEF pane, which QR cannot observe). Frontend-side clipboard provenance
	 *  (only re-checking content QR can prove it wrote itself) gates whether
	 *  this command is even called -- not re-validated here, since gate3's own
	 *  fact-identity cascade only ever concerns itself with message.content,
	 *  never the OS clipboard.
	 * 
	 *  No-ops (returns approved, no new review) when the newly-active provider
	 *  set's max risk is not STRICTLY HIGHER than what the original review
	 *  already covered (messages.reviewed_at_risk_rating) -- a same-or-lower-
	 *  risk destination needs no re-check.
	 */
	recheckTier3ProviderSelection: (request: RecheckTier3ProviderSelectionRequest) => typedError<Gate3ReviewResult, string>(__TAURI_INVOKE("recheck_tier3_provider_selection", { request })),
	/**
	 *  items.id=416 (decisions.id=766): extends Gate3 review to every native
	 *  copy path on ChatPane's transcript (Ctrl+C / right-click-copy), not just
	 *  the dedicated "Copy starter" button -- previously an already-`approved`
	 *  message got zero re-protection against a plain manual copy, and a
	 *  `withheld` message (durable, permanently persisted) rendered identically
	 *  to `approved` with no protection at all. See ChatPane.tsx's own copy
	 *  (`copy` event) handler for the click-initiated-only trigger this
	 *  responds to -- never fired outside a user's own copy gesture on QR's own
	 *  rendered content, never a poll, per the same locked
	 *  no-passive-clipboard-monitoring rule handleCopyStarter documents.
	 * 
	 *  Unlike request_tier3_gate3_review, there is no single message row to
	 *  read from -- a selection may span multiple messages (items.id=416's
	 *  cross-message-selection resolution: treated as ONE new composition, one
	 *  combined review, not fragmented per-message sub-reviews) -- so
	 *  content_text is supplied directly by the frontend (the concatenated
	 *  selection) rather than looked up by id, and content_key/focus_run_id are
	 *  synthesized labels for the disclosure_log audit row, not references to
	 *  any persisted row (confirmed in gate3.rs: neither is used for a DB
	 *  lookup, only pushed into the audit entry's fields_shared/fields_withheld).
	 * 
	 *  Parameter sourcing mostly mirrors request_tier3_gate3_review's own
	 *  quick-ask constants (content_sensitivity_severity=1, execution_tier=1) --
	 *  both are fixed placeholders reflecting the absence of a PersonalTrack at
	 *  this call site, not a claim about the reviewed content's structure. Like
	 *  request_tier3_gate3_review, this command reviews arbitrary
	 *  message/clipboard content, not Quick-Ask-Focus output specifically;
	 *  quick-ask.focus's identifiers are borrowed only as a synthetic label. This
	 *  command does NOT mirror request_tier3_gate3_review's target_tier=3 --
	 *  confirmed live (2026-09-04) that reusing 3 unconditionally makes gate3's
	 *  own zero_spans_safe_to_auto_approve (destination_risk >= 3 forces High
	 *  review regardless of content) fire for every single copy when no Tier 3
	 *  provider pane happens to be open, defeating the "silent on a fast,
	 *  unflagged pass" UX this whole feature is built around: request_tier3_gate3_review's
	 *  target_tier=3 is correct there because that flow's own precondition is
	 *  "the user is literally about to access Tier 3" (its own doc comment) -- a
	 *  native copy gesture on this transcript carries no such precondition; the
	 *  destination could just as easily be a text editor as a Tier 3 pane.
	 *  target_tier=1 here means an unknown/no-Tier-3-destination copy is judged
	 *  on its own content severity alone (correct, most copies pass silently and
	 *  fast), while destination_risk_rating below still reflects any ACTUALLY
	 *  active Tier 3 provider's real risk -- so a copy made while a genuinely
	 *  risky destination is open still gets the stricter review, preserving
	 *  decisions.id=755's original intent for that real case.
	 *  severity_authoritative=false (items.id=458, corrected scope of the
	 *  earlier items.id=799): content_sensitivity_severity=1 being a placeholder
	 *  means destination_risk alone must not force the High-tier gate on zero PF
	 *  spans -- an empty, uninformative interrupt on an otherwise silent copy.
	 *  This command intentionally does NOT touch messages.gate3_review_status
	 *  or messages.reviewed_at_risk_rating -- those track a single drafted
	 *  message's own lifecycle; a copy-triggered review is a fresh, ephemeral
	 *  check with no message row of its own to update.
	 */
	requestChatCopyGate3Review: (request: RequestChatCopyGate3ReviewRequest) => typedError<Gate3ReviewResult, string>(__TAURI_INVOKE("request_chat_copy_gate3_review", { request })),
	getOnboardingFocusSuggestions: (personas: string[]) => typedError<NotImplementedPlaceholder, string>(__TAURI_INVOKE("get_onboarding_focus_suggestions", { personas })),
	submitOnboardingPersonaSelection: (personas: string[]) => typedError<string[], string>(__TAURI_INVOKE("submit_onboarding_persona_selection", { personas })),
	submitOnboardingFocusSelection: (focusSelections: NotImplementedPlaceholder[]) => typedError<string[], string>(__TAURI_INVOKE("submit_onboarding_focus_selection", { focusSelections })),
	listPersonas: (userId: string) => typedError<PersonaInfo[], string>(__TAURI_INVOKE("list_personas", { userId })),
	createPersona: (request: CreatePersonaRequest) => typedError<CreatePersonaResponse, string>(__TAURI_INVOKE("create_persona", { request })),
	listFocuses: (userId: string, personaId: string) => typedError<FocusInfo[], string>(__TAURI_INVOKE("list_focuses", { userId, personaId })),
	/**
	 *  get_focus_settings takes both persona_id and focus_id — the store key is
	 *  composite. The IPC spec lists focus_id only (higher-level abstraction).
	 */
	getFocusSettings: (userId: string, personaId: string, focusId: string) => typedError<FocusInfo, string>(__TAURI_INVOKE("get_focus_settings", { userId, personaId, focusId })),
	/**
	 *  Applies a Focus settings change directly, UNLESS the change would loosen
	 *  privacy_tier or move focus_profile to 'protected' -- in which case this
	 *  returns Err(json-serialized FrictionGateDetail) instead of applying
	 *  anything, and the frontend must route the user through
	 *  commands::consent::submit_friction_gate_decision to either apply the
	 *  change (decision="proceed") or drop it (decision="cancel"). See module
	 *  header for the full flow and the tier-direction note.
	 * 
	 *  The error string is JSON (FrictionGateDetail serialized), not a plain
	 *  message -- distinguishable from every other error this command can
	 *  return (validation failures, not_found) by attempting a JSON parse.
	 *  A frontend that doesn't parse it still gets a readable-enough string,
	 *  but the structured shape is what submit_friction_gate_decision expects
	 *  to be built from.
	 */
	updateFocusSettings: (userId: string, request: UpdateFocusSettingsRequest) => typedError<FocusInfo, string>(__TAURI_INVOKE("update_focus_settings", { userId, request })),
	getActiveBoard: (userId: string, personaId: string) => typedError<ActiveBoardResponse, string>(__TAURI_INVOKE("get_active_board", { userId, personaId })),
	getTopicList: (focusId: string, userId: string, personaId: string) => typedError<TopicInfo[], string>(__TAURI_INVOKE("get_topic_list", { focusId, userId, personaId })),
	updateTopicState: (request: UpdateTopicStateRequest) => typedError<null, string>(__TAURI_INVOKE("update_topic_state", { request })),
	getPersonalFields: (personaId: string, userId: string) => typedError<PersonalFieldInfo[], string>(__TAURI_INVOKE("get_personal_fields", { personaId, userId })),
	updatePersonalField: (request: UpdatePersonalFieldRequest) => typedError<PersonalFieldInfo, string>(__TAURI_INVOKE("update_personal_field", { request })),
	getVoiceProfile: (personaId: string, userId: string) => typedError<VoiceProfileInfo, string>(__TAURI_INVOKE("get_voice_profile", { personaId, userId })),
	/**
	 *  Lists active outputs, optionally filtered by focus_id, topic_id, and/or
	 *  output_type. Wired to output_store::list_outputs() (items.id=91, part 1).
	 * 
	 *  `source`: None defaults to 'qr_generated' -- this is decisions.id=486's
	 *  "excluded from default Library view" rule (items.id=383): an ingested
	 *  document only appears when the caller explicitly asks for
	 *  source=Some("external_ingested") (the future Imported view). This default
	 *  is applied here, not in output_store::list_outputs, which treats None as
	 *  "no filter" like its other parameters.
	 * 
	 *  Enforces focus_settings.focus_profile visibility on top of output_store's
	 *  results -- outputs owned by a 'protected' Focus are excluded (items.id=230).
	 *  See module header.
	 */
	listOutputs: (userId: string, personaId: string, focusId: string | null, topicId: string | null, outputType: string | null, source: string | null) => typedError<OutputInfo[], string>(__TAURI_INVOKE("list_outputs", { userId, personaId, focusId, topicId, outputType, source })),
	/**
	 *  Enforces focus_settings.focus_profile visibility -- an output owned by a
	 *  'protected' Focus returns the same "not_found" error a genuinely missing
	 *  id would (items.id=230); a Protected output must not be distinguishable
	 *  from a nonexistent one by its error.
	 */
	getOutput: (outputId: string, userId: string, personaId: string) => typedError<OutputInfo, string>(__TAURI_INVOKE("get_output", { outputId, userId, personaId })),
	/**
	 *  Deletes an output (items.id=91, part 2, complete 2026-07-26). Soft-delete
	 *  only -- content is zeroed and status set to 'deleted'; the row is never
	 *  hard-deleted (architecture Section 3.4, output_store::delete_output).
	 * 
	 *  deep_purge: accepted for command-contract stability but NOT implemented.
	 *  Passing Some(true) returns Err("deep_purge_not_implemented"). See
	 *  output_store::delete_output's doc comment for why this is deliberately
	 *  out of scope for R1.
	 */
	deleteOutput: (outputId: string, userId: string, personaId: string, deepPurge: boolean | null) => typedError<null, string>(__TAURI_INVOKE("delete_output", { outputId, userId, personaId, deepPurge })),
	/**
	 *  Thin IPC wrapper -- the actual system-clipboard write via
	 *  tauri-plugin-clipboard-manager. See prepare_clipboard_copy for the real
	 *  (tested) logic.
	 */
	copyOutputToClipboard: (outputId: string, userId: string, personaId: string) => typedError<null, string>(__TAURI_INVOKE("copy_output_to_clipboard", { outputId, userId, personaId })),
	getFocusBuilderSession: (focusId: string | null) => typedError<NotImplementedPlaceholder, string>(__TAURI_INVOKE("get_focus_builder_session", { focusId })),
	submitFocusBuilderStep: (sessionId: string, input: NotImplementedPlaceholder) => typedError<NotImplementedPlaceholder, string>(__TAURI_INVOKE("submit_focus_builder_step", { sessionId, input })),
	/**
	 *  Report configuration state for a Tier 2 provider. Returns
	 *  configured=false (not an error) when no key is set yet -- an
	 *  unconfigured provider is a normal, expected state, not a failure.
	 */
	getTier2Config: (provider: string) => typedError<Tier2Config, string>(__TAURI_INVOKE("get_tier2_config", { provider })),
	/**  Set (or replace) the credential for a Tier 2 provider, user-global scope. */
	setTier2Provider: (provider: string, apiKey: string) => typedError<null, string>(__TAURI_INVOKE("set_tier2_provider", { provider, apiKey })),
	/**
	 *  Set (or clear, with `provider: None`) the current user's Tier 2 provider
	 *  preference -- distinct from set_tier2_provider above, which stores a
	 *  credential. This is the "which provider should QR actually use" choice.
	 * 
	 *  items.id=432: lifecycle.rs resolves an account-wide user_provider_preference
	 *  row via find_preferred_provider()/resolve_preference() (items.id=428/432)
	 *  instead of the legacy users.tier2_provider_preference column (dropped by
	 *  items.id=433 -- this command wrote it as a dual-write in the interim, now
	 *  removed along with the column). Selecting a provider marks its
	 *  account-wide row Preferred and downgrades any OTHER Tier 1.5 candidate's
	 *  account-wide row that was previously Preferred to Allowed, preserving
	 *  find_preferred_provider()'s "at most one Preferred" assumption. Clearing
	 *  (`provider: None`) downgrades any currently-Preferred candidate the same
	 *  way, without picking a new one.
	 */
	setTier2ProviderPreference: (provider: string | null) => typedError<null, string>(__TAURI_INVOKE("set_tier2_provider_preference", { provider })),
	/**
	 *  List every provider preference row for the current user, across every
	 *  scope (account-wide, Persona-wide, Focus-specific) -- for a future
	 *  settings-surface listing. items.id=254 Part 1.
	 */
	getTier2ProviderPreferences: () => typedError<UserProviderPreference[], string>(__TAURI_INVOKE("get_tier2_provider_preferences")),
	dismissNotification: (notificationId: string) => typedError<null, string>(__TAURI_INVOKE("dismiss_notification", { notificationId })),
	login: (displayName: string, password: string) => typedError<null, string>(__TAURI_INVOKE("login", { displayName, password })),
	logout: () => typedError<null, string>(__TAURI_INVOKE("logout")),
	/**
	 *  Derive and return the current session's recovery mnemonic for one-time
	 *  display. Section 8.5's Option B: `Mnemonic::from_entropy()` on the raw
	 *  32-byte master key directly, not a wrapper key -- `Mnemonic::parse()` on
	 *  the returned phrase later recovers the exact original bytes, no
	 *  unwrapping step. Requires a resident session (KeyRegistry) the same way
	 *  tier2::get_tier2_config does; "not logged in" is the same error string
	 *  for the same reason -- there is no key to derive a mnemonic from yet.
	 */
	getRecoveryKeyDisplay: () => typedError<RecoveryKeyDisplay, string>(__TAURI_INVOKE("get_recovery_key_display")),
	/**
	 *  Read back the current session's identity (items.id=267), if any.
	 *  `Ok(None)` -- not `Err` -- is the expected result on every cold app
	 *  launch: the master key is never persisted (CLAUDE.md), so KeyRegistry
	 *  starts empty every process lifetime and there is no auto-relogin. `Err`
	 *  is reserved for a real query failure, including the internal
	 *  inconsistency of a resident user_id with no matching users row (should
	 *  be impossible -- same reasoning login()'s "account exists with no salt
	 *  record" branch uses).
	 */
	getSession: () => typedError<{
	user_id: string,
	display_name: string,
	role: string,
	is_primary: boolean,
} | null, string>(__TAURI_INVOKE("get_session")),
	/**
	 *  Record activity on the resident account's live session(s) (items.id=311).
	 *  Called by a debounced frontend listener (mouse/keyboard/scroll/click),
	 *  not on every IPC command -- see auth::idle_timeout's own module header
	 *  for why a frontend-driven activity signal was chosen over a backend-
	 *  command-tracked one. A no-op, not an error, when nobody is logged in --
	 *  a stray ping racing a logout is expected, not exceptional.
	 */
	recordActivity: () => typedError<null, string>(__TAURI_INVOKE("record_activity")),
	getHealth: () => typedError<HealthResponse, string>(__TAURI_INVOKE("get_health")),
	getCapabilityProfile: () => typedError<CapabilityProfileResponse, string>(__TAURI_INVOKE("get_capability_profile")),
	/**
	 *  The selector screen's primary read path (TIER3_ACCESS_MODEL.md State 3,
	 *  items.id=202 piece 1's remaining wiring) -- replaces
	 *  tier3AccessConfig.ts's PLACEHOLDER_PROVIDERS stand-in array.
	 * 
	 *  items.id=488: provider_store::list_active_providers() returns every
	 *  activation_status='active' row regardless of provider_type -- correct
	 *  for that function's other caller (focus_provider_criteria_store's
	 *  eligible_providers_for_focus, which deliberately wants the full active
	 *  pool including cloud_inference_api rows), but wrong here. This screen is
	 *  the Tier 2/Tier 3 pane selector specifically, so it must only surface
	 *  the two provider_type shapes lane_str() knows how to label
	 *  ('split_screen_web' -> tier2, 'external_service' -> tier3) -- filtered
	 *  out here rather than in the shared store function, so cloud_inference_api
	 *  (Tier 1.5: groq/mistral) and local_model rows never reach this list.
	 */
	listActiveProviders: () => typedError<Tier3ProviderSummary[], string>(__TAURI_INVOKE("list_active_providers")),
	/**
	 *  Opens one pane per confirmed provider selection (items.id=223's actual
	 *  trigger -- nothing in tier3_pane/ creates a pane except in response to
	 *  this). `launch_url` is looked up server-side; the frontend only ever
	 *  passes provider IDs. Best-effort across the batch: the first provider
	 *  that fails to resolve or send aborts the remaining opens rather than
	 *  silently skipping them, since a partial open would leave the selector's
	 *  own "confirmed" state and the actual open panes disagreeing about what's
	 *  open. Cookie restore (items.id=224 resolution) is a separate, narrower
	 *  best-effort layer within each iteration -- see restore_cookies_into_jar's
	 *  own doc on why that failure mode does NOT abort the batch the same way.
	 * 
	 *  Dispatch is a single `AppHandle::run_on_main_thread` call per provider
	 *  (items.id=202 real positioning fix, 2026-08-07) -- unlike the old
	 *  `EventLoopProxy::send_event`, this both queues the work AND guarantees it
	 *  runs promptly: `run_on_main_thread` is Tauri/tao's own main-thread
	 *  dispatch queue, serviced as part of GTK's ordinary main-loop operation,
	 *  not a queue that needed a *separate* explicit wake call to be noticed
	 *  (see the old design's now-deleted note here about a real, empirically
	 *  confirmed dispatch-delay bug that required exactly that workaround).
	 */
	openTier3Panes: (providerIds: string[]) => typedError<null, string>(__TAURI_INVOKE("open_tier3_panes", { providerIds })),
	/**
	 *  Closes one pane by provider ID. A no-op (not an error) if that provider
	 *  has no open pane -- `PaneManager::close_pane` already tolerates this
	 *  (pane_host.rs), and a caller racing a close against an already-closed
	 *  pane is a normal condition, not a failure. See open_tier3_panes' doc on
	 *  why a single `run_on_main_thread` call is dispatch and guaranteed-prompt
	 *  delivery in one step now.
	 * 
	 *  items.id=330: the close dispatch runs FIRST, cookie persist (items.id=224
	 *  resolution) after -- confirmed live this session (visible ~1s delay
	 *  before a closed pane actually stopped compositing on a newly-navigated-to
	 *  tab) that the previous persist-then-close ordering held the pane
	 *  on-screen for however long `persist_cookies_from_jar`'s cookie-jar round
	 *  trip took (up to `COOKIE_OP_TIMEOUT`, 500ms, per pane). Safe to reorder:
	 *  `persist_cookies_from_jar` reads CEF's *global* cookie manager by URL
	 *  (`cookie_manager_get_global_manager`), not anything tied to this specific
	 *  pane's `Browser` instance, so it works identically whether the browser
	 *  has already been torn down or not. Its failure is still only ever
	 *  logged, never a reason this command returns an error.
	 */
	closeTier3Pane: (providerId: string) => typedError<null, string>(__TAURI_INVOKE("close_tier3_pane", { providerId })),
	/**
	 *  items.id=202 piece 4, real positioning fix 2026-08-07 -- stores the
	 *  frontend's live layout fractions (unchanged `PaneRectFraction` semantics:
	 *  fraction of the whole window's content area) and requests a redraw so the
	 *  GLArea's own `render` callback (pane_host.rs) picks up the new layout on
	 *  its very next tick. Called whenever the frontend's pane-dock region
	 *  resizes or `openPaneIds` changes (a different pane count changes the
	 *  column split even at the same dock size).
	 * 
	 *  No window-geometry query here anymore. The old version queried
	 *  `window.inner_position()`/`inner_size()` to build an absolute
	 *  `PhysicalRect` for a separate OS window to sync against -- confirmed
	 *  broken on Wayland (pinned, wrong origin/size on this dev machine's
	 *  KDE/Wayland session) and the exact code this rewrite deletes rather than
	 *  patches. Under single-window compositing every pane's target is already
	 *  expressed relative to the GLArea's own size (render.rs's `render()`
	 *  reads `PaneLayoutState` directly), so there is nothing left to query.
	 */
	setPaneLayout: (layout: PaneLayoutEntry[]) => typedError<null, string>(__TAURI_INVOKE("set_pane_layout", { layout })),
	/**
	 *  items.id=359 pieces 4/5: makes `provider_id` (or none, to collapse to
	 *  the empty state) the one pane actually composited in the content
	 *  pane -- the rail+content-pane model's core mechanic. `None` no-ops if
	 *  nothing is active; a `provider_id` naming a pane that isn't currently
	 *  open (e.g. a race against a just-closed pane) is likewise a no-op at
	 *  the `pane_host::PaneManager::set_active_pane` layer (`panes.get_mut`
	 *  simply finds nothing), not an error -- same "a stale reference to a
	 *  pane is a normal race, not a failure" framing `close_tier3_pane`
	 *  already documents.
	 */
	setActivePane: (providerId: string | null) => typedError<null, string>(__TAURI_INVOKE("set_active_pane", { providerId })),
	/**
	 *  Forwards one mouse-button transition inside an open pane's on-screen
	 *  rect, hit-tested natively by the browser's own DOM (items.id=257 Path
	 *  B) -- the frontend's invisible per-pane hit-layer, one
	 *  absolutely-positioned `<div>` per open pane, kept in sync with the exact
	 *  same `PaneRectFraction` geometry `set_pane_layout` already reports (see
	 *  `paneLayout.ts`). Replaces the GDK input-shape click-routing mechanism
	 *  (items.id=257 Path A), which froze the whole client's Wayland pointer
	 *  input the moment it was given a non-empty region -- root-caused this
	 *  session (see pane_host.rs's module doc) to GDK's non-native child
	 *  windows never getting a real Wayland compositor surface to route input
	 *  to.
	 * 
	 *  `x`/`y` arrive already pane-local, in the pane hit-div's own CSS pixel
	 *  space (`PointerEvent.offsetX`/`offsetY`) -- CSS pixels are the DOM's
	 *  device-independent unit, the same logical-pixel convention CEF's
	 *  `MouseEvent` expects, so no origin-subtraction or scale-factor division
	 *  is needed here the way the deleted GDK-path `cef_mouse_event` required:
	 *  the browser's own hit-testing already did the pane-scoping a GDK-side
	 *  `hit_test_pane` used to be needed for.
	 * 
	 *  A no-op (not an error) if `provider_id` names a pane that has already
	 *  closed by the time this arrives -- an event racing a close is expected,
	 *  not a failure, matching `close_tier3_pane`'s own framing.
	 */
	forwardPaneMouseClick: (providerId: string, x: number | null, y: number | null, button: PaneMouseButton, mouseup: boolean, clickCount: number, buttons: number, modifiers: PaneEventModifiers) => typedError<null, string>(__TAURI_INVOKE("forward_pane_mouse_click", { providerId, x, y, button, mouseup, clickCount, buttons, modifiers })),
	/**
	 *  Forwards a pointer move (or leave) inside an open pane's on-screen rect.
	 *  See `forward_pane_mouse_click`'s doc for the coordinate/no-op contract,
	 *  which this shares. The frontend coalesces these to at most one per
	 *  animation frame before sending -- the native GDK path this replaces ran
	 *  in-process at whatever rate the OS reported; this path crosses an IPC
	 *  boundary per call, so batching to the frame rate the compositor can
	 *  actually show avoids flooding it without a perceptible behavior change.
	 */
	forwardPaneMouseMove: (providerId: string, x: number | null, y: number | null, leaving: boolean, buttons: number, modifiers: PaneEventModifiers) => typedError<null, string>(__TAURI_INVOKE("forward_pane_mouse_move", { providerId, x, y, leaving, buttons, modifiers })),
	/**
	 *  Forwards a wheel/scroll event inside an open pane's on-screen rect. See
	 *  `forward_pane_mouse_click`'s doc for the coordinate/no-op contract.
	 *  Unlike mouse-move, not throttled by the frontend -- CEF's own
	 *  scroll-momentum handling needs per-event delta fidelity, the same reason
	 *  the deleted GDK scroll handler forwarded every `scroll-event` unthrottled.
	 */
	forwardPaneMouseWheel: (providerId: string, x: number | null, y: number | null, deltaX: number | null, deltaY: number | null, modifiers: PaneEventModifiers) => typedError<null, string>(__TAURI_INVOKE("forward_pane_mouse_wheel", { providerId, x, y, deltaX, deltaY, modifiers })),
	/**
	 *  Forwards one keyboard event into an open pane's CEF browser, once it has
	 *  DOM focus (`PaneHitLayer.tsx`'s per-pane hit-div already claims focus on
	 *  pointerdown, same element `forward_pane_mouse_click` fires from -- no
	 *  separate focus IPC call needed on the frontend side).
	 * 
	 *  `windows_key_code` comes from the DOM `KeyboardEvent.keyCode` -- despite
	 *  being deprecated, it still follows the long-standing web-platform
	 *  convention of matching Windows virtual-key codes across engines, which is
	 *  exactly what CEF's `KeyEvent::windows_key_code` expects regardless of
	 *  platform. There is no real native/hardware keycode available here (input
	 *  arrives over IPC from a DOM event, not a native GTK/X11 event) --
	 *  `pane_host.rs`'s dispatch arm mirrors `windows_key_code` into CEF's
	 *  `native_key_code` as a documented best-effort stand-in rather than
	 *  leaving it zeroed or building a DOM-`code`-to-X11-keycode lookup table,
	 *  per items.id=332's scoping: enough to type into a login form, not
	 *  accelerator-perfect native-scancode fidelity.
	 * 
	 *  `character` is 0 for non-printable keys (arrows, Enter, Backspace, ...)
	 *  and the key's single UTF-16 code unit otherwise -- the frontend sends a
	 *  `RawKeyDown` for every keydown, followed by a `Char` call only when
	 *  `character != 0`, mirroring CEF's own RAWKEYDOWN-then-CHAR convention for
	 *  text input.
	 * 
	 *  Same no-op-on-already-closed-pane contract as `forward_pane_mouse_click`.
	 */
	forwardPaneKey: (providerId: string, eventType: PaneKeyEventType, windowsKeyCode: number, character: number, modifiers: PaneEventModifiers) => typedError<null, string>(__TAURI_INVOKE("forward_pane_key", { providerId, eventType, windowsKeyCode, character, modifiers })),
	/**
	 *  items.id=364: steps an open pane's CEF zoom level up/down/reset (a
	 *  per-pane `f64` tracked in `PaneState`, see `pane_host.rs`) by forwarding
	 *  straight to `BrowserHost::set_zoom_level` -- the same mechanism a normal
	 *  browser's own Ctrl+=/Ctrl+-/Ctrl+0 accelerator would use, just driven from
	 *  this app's own frontend since CEF's Chrome-runtime browser has no browser
	 *  chrome of its own to bind that accelerator (see `ZoomDirection`'s own
	 *  doc). Does not reach a pane's popup, if it has one open -- popups get the
	 *  same `DEFAULT_ZOOM_LEVEL` applied once at creation (pane_host.rs's
	 *  `drain_popup_events`, items.id=366), but aren't wired to this command's
	 *  live in/out/reset stepping: they're short-lived OAuth login surfaces
	 *  (items.id=234), not something a user is expected to sit and adjust.
	 */
	adjustPaneZoom: (providerId: string, direction: ZoomDirection) => typedError<null, string>(__TAURI_INVOKE("adjust_pane_zoom", { providerId, direction })),
	/**
	 *  items.id=234: popup counterpart to `forward_pane_mouse_click` -- same
	 *  coordinate/no-op contract, except `x`/`y` are local to the popup's own
	 *  on-screen rect (`tier3-popup-opened`'s reported `rect`), not the parent
	 *  pane's. `provider_id` names the *parent* pane (popups have no separate
	 *  id-keyspace, see `PaneManager.popups`'s own doc, pane_host.rs).
	 */
	forwardPopupMouseClick: (providerId: string, x: number | null, y: number | null, button: PaneMouseButton, mouseup: boolean, clickCount: number, buttons: number, modifiers: PaneEventModifiers) => typedError<null, string>(__TAURI_INVOKE("forward_popup_mouse_click", { providerId, x, y, button, mouseup, clickCount, buttons, modifiers })),
	/**  items.id=234: popup counterpart to `forward_pane_mouse_move`. */
	forwardPopupMouseMove: (providerId: string, x: number | null, y: number | null, leaving: boolean, buttons: number, modifiers: PaneEventModifiers) => typedError<null, string>(__TAURI_INVOKE("forward_popup_mouse_move", { providerId, x, y, leaving, buttons, modifiers })),
	/**  items.id=234: popup counterpart to `forward_pane_mouse_wheel`. */
	forwardPopupMouseWheel: (providerId: string, x: number | null, y: number | null, deltaX: number | null, deltaY: number | null, modifiers: PaneEventModifiers) => typedError<null, string>(__TAURI_INVOKE("forward_popup_mouse_wheel", { providerId, x, y, deltaX, deltaY, modifiers })),
	/**
	 *  items.id=367: popup counterpart to `forward_pane_key` -- same
	 *  windows_key_code/character/RawKeyDown-then-Char contract, see that
	 *  command's own doc. Missing entirely until now: `PopupHitLayer.tsx` only
	 *  ever forwarded mouse click/move/wheel (items.id=234's original scope),
	 *  so a popup could be clicked into and focused but never actually typed
	 *  into -- confirmed by Jason live, 2026-08-30 (Claude's Google sign-in
	 *  popup accepted focus/clicks but no keystrokes reached it, reproducing
	 *  even via a plain in-app pane switch away and back, not just after an
	 *  OS-level focus round-trip).
	 */
	forwardPopupKey: (providerId: string, eventType: PaneKeyEventType, windowsKeyCode: number, character: number, modifiers: PaneEventModifiers) => typedError<null, string>(__TAURI_INVOKE("forward_popup_key", { providerId, eventType, windowsKeyCode, character, modifiers })),
	sendMessage: (request: SendMessageRequest) => typedError<MessageInfo[], string>(__TAURI_INVOKE("send_message", { request })),
	listMessages: (userId: string, personaId: string, contextKey: string) => typedError<MessageInfo[], string>(__TAURI_INVOKE("list_messages", { userId, personaId, contextKey })),
	/**
	 *  Configure (or reconfigure) this install's folder-sync destination for a
	 *  (persona_id, group_id) pair. Upsert -- see
	 *  group_sync::settings_store::set_group_sync_folder's own doc comment.
	 */
	setGroupSyncFolder: (personaId: string, groupId: string, folderPath: string) => typedError<null, string>(__TAURI_INVOKE("set_group_sync_folder", { personaId, groupId, folderPath })),
	/**
	 *  Fetch this install's folder-sync settings for a (persona_id, group_id)
	 *  pair. Returns Ok(None) if sync has never been configured for this pair
	 *  -- not an error, matching get_focus_settings-style "None is a valid
	 *  state" shape for a settings row that may genuinely not exist yet.
	 */
	getGroupSyncFolder: (personaId: string, groupId: string) => typedError<{
	folder_path: string,
	last_synced_at: string | null,
	last_error: string | null,
	updated_at: string,
} | null, string>(__TAURI_INVOKE("get_group_sync_folder", { personaId, groupId })),
	/**
	 *  Remove a member from a group (or record their own departure): rotates
	 *  the group's symmetric key and queues redistribution to remaining
	 *  members via the same asymmetric-keypair envelope mechanism item 284's
	 *  invitation flow uses (items.id=288, group.db 266f). Does not itself
	 *  rekey any local group.db file -- see auth::group_membership's own module
	 *  header (TWO HALVES) for why that happens separately, per remaining
	 *  member, via the periodic poll loop in main.rs.
	 * 
	 *  `reason` is "left" or "removed" -- any other value is rejected with a
	 *  string error before reaching group_membership::remove_member.
	 * 
	 *  No group-admin/permission model gates who may call this -- there is no
	 *  group-admin concept anywhere in this schema yet; building one is a
	 *  separate scope decision, not made here (known limitation, not silently
	 *  assumed away).
	 */
	removeGroupMember: (groupId: string, departingPersonaId: string, reason: string, senderLabel: string) => typedError<null, string>(__TAURI_INVOKE("remove_group_member", { groupId, departingPersonaId, reason, senderLabel })),
	/**
	 *  Create a new group: generates its symmetric key and id, materializes the
	 *  creator's own local group.db, and establishes the creator's own
	 *  membership state (items.id=291). See auth::group_creation's own module
	 *  header for the full design, including how the creator's own membership
	 *  is made visible to group_membership::remaining_members.
	 * 
	 *  The caller must currently be logged in as `creator_persona_id`'s owning
	 *  account -- returns an error otherwise, rather than silently failing
	 *  later when personal.db can't be opened.
	 */
	createGroup: (creatorPersonaId: string, groupDisplayName: string, creatorLabel: string) => typedError<string, string>(__TAURI_INVOKE("create_group", { creatorPersonaId, groupDisplayName, creatorLabel })),
	/**
	 *  Opt (or opt back out) `persona_id`'s context assembly into checking
	 *  `group_id`'s facts. One-time-per-persona decision (Section 3.2) -- not
	 *  re-evaluated per Focus run; conductor::lifecycle::build_personal_track()
	 *  reads this table once per run and separately checks whether the group's
	 *  key is currently resident (auth::registry::GroupKeyRegistry) before
	 *  actually loading anything.
	 */
	setGroupFactSourceOptIn: (personaId: string, groupId: string, optedIn: boolean) => typedError<null, string>(__TAURI_INVOKE("set_group_fact_source_opt_in", { personaId, groupId, optedIn })),
	/**  Every group_id `persona_id` is currently opted into. */
	getGroupFactSources: (personaId: string) => typedError<string[], string>(__TAURI_INVOKE("get_group_fact_sources", { personaId })),
	/**
	 *  Group 23 -- History screen's Group row (items.id=404). Every group_id
	 *  `persona_id` currently holds a durable key for -- actual group
	 *  membership, distinct from get_group_fact_sources' opt-in-to-facts
	 *  subset above (a persona can be a group member without having opted
	 *  that group's facts into its own context assembly). Frontend-facing
	 *  existence/count check only: deliberately strips group_key_hex (key
	 *  material) and created_at, returning bare ids -- see GroupKeyRow's own
	 *  fields. No group-metadata table exists anywhere to resolve these ids
	 *  to a real display name -- that's items.id=407's scope, not this one's.
	 */
	listPersonaGroupIds: (personaId: string) => typedError<string[], string>(__TAURI_INVOKE("list_persona_group_ids", { personaId })),
	/**
	 *  Configure (or reconfigure) this install's folder-sync destination for a
	 *  (persona_id, share_id) pair. `role` is "owner" or "recipient" -- see
	 *  settings_store::set_persona_share_sync_folder's own doc comment on why a
	 *  reconfigure may not change it. Upsert on folder_path.
	 */
	setPersonaShareSyncFolder: (personaId: string, shareId: string, role: string, folderPath: string) => typedError<null, string>(__TAURI_INVOKE("set_persona_share_sync_folder", { personaId, shareId, role, folderPath })),
	/**
	 *  Fetch this install's folder-sync settings for a (persona_id, share_id)
	 *  pair. Returns Ok(None) if sync has never been configured for this pair
	 *  -- not an error, matching get_group_sync_folder's "None is a valid
	 *  state" shape.
	 */
	getPersonaShareSyncFolder: (personaId: string, shareId: string) => typedError<{
	role: string,
	folder_path: string,
	last_synced_at: string | null,
	last_pushed_at: string | null,
	last_content_hash: string | null,
	last_error: string | null,
	updated_at: string,
} | null, string>(__TAURI_INVOKE("get_persona_share_sync_folder", { personaId, shareId })),
	/**
	 *  Configure (or reconfigure) this install's folder-sync source location for
	 *  a (recipient_user_id, share_id) pair. Upsert on folder_path.
	 */
	setPersonaViewShareSyncFolder: (recipientUserId: string, shareId: string, folderPath: string) => typedError<null, string>(__TAURI_INVOKE("set_persona_view_share_sync_folder", { recipientUserId, shareId, folderPath })),
	/**
	 *  Fetch this install's folder-sync settings for a (recipient_user_id,
	 *  share_id) pair. Returns Ok(None) if sync has never been configured for
	 *  this pair -- not an error, matching get_persona_share_sync_folder's
	 *  "None is a valid state" shape.
	 */
	getPersonaViewShareSyncFolder: (recipientUserId: string, shareId: string) => typedError<{
	folder_path: string,
	last_error: string | null,
	updated_at: string,
} | null, string>(__TAURI_INVOKE("get_persona_view_share_sync_folder", { recipientUserId, shareId })),
	/**
	 *  Store an uploaded/ingested document: writes its bytes to an encrypted
	 *  blob on disk (ingest_blob), creates a lightweight ingest-only focus_run,
	 *  and writes the outputs.db row (source='external_ingested').
	 * 
	 *  Exactly one of `content` (direct paste) or `file_path` (from an OS file
	 *  picker -- the frontend resolves the path, this command just reads it) is
	 *  required, mirroring decisions.id=491's own validation rule for the
	 *  future `ingest_document`.
	 * 
	 *  `focus_slug`: the real Focus the user filed this document under (may be
	 *  any string the frontend supplies -- focus_id/focus_slug carry no FK in
	 *  this codebase, see output_store::INGEST_PSEUDO_FOCUS_ID's own doc
	 *  comment). `sensitivity`: required, no default -- see
	 *  output_store::save_ingested_output's VALID_SENSITIVITY check; this build
	 *  does no automatic content classification (that is decisions.id=488's
	 *  extraction pass, out of scope here), so silently defaulting to "general"
	 *  for a potentially sensitive upload would be the wrong failure direction.
	 */
	storeIngestedDocument: (userId: string, personaId: string, focusSlug: string, projectEntityId: string | null, sensitivity: string, content: string | null, filePath: string | null) => typedError<StoreIngestedDocumentResponse, string>(__TAURI_INVOKE("store_ingested_document", { userId, personaId, focusSlug, projectEntityId, sensitivity, content, filePath })),
	/**
	 *  Retrieve an ingested document's current-version bytes, decrypted.
	 *  Applies the same Focus-profile visibility check as
	 *  commands::library::get_output (see visibility_focus_id there) -- a
	 *  Protected-Focus ingested document must be exactly as unreachable as a
	 *  Protected-Focus QR-generated output.
	 * 
	 *  No chunking/streaming -- returns the whole file as a JSON byte array (no
	 *  base64 crate is in Cargo.toml today). Acceptable for typical document
	 *  sizes; a known, accepted efficiency tradeoff for larger files, not fixed
	 *  here.
	 */
	getIngestedDocumentBytes: (outputId: string, userId: string, personaId: string) => typedError<number[], string>(__TAURI_INVOKE("get_ingested_document_bytes", { outputId, userId, personaId })),
	/**
	 *  Starts a new chat for a Persona. decisions.id=739: the previously
	 *  current chat is not touched by this call at all -- its messages stay
	 *  exactly where they were saved (message_store::save_message persists
	 *  per-message, not per-chat-on-close), so "new chat auto-saves to
	 *  history" is satisfied by this command simply handing back a fresh
	 *  chat_id/context_key, not by any explicit save step here.
	 */
	createChat: (userId: string, personaId: string) => typedError<ChatInfo, string>(__TAURI_INVOKE("create_chat", { userId, personaId })),
	/**  Lists a Persona's non-archived chats, most-recent-first. */
	listChats: (userId: string, personaId: string) => typedError<ChatInfo[], string>(__TAURI_INVOKE("list_chats", { userId, personaId })),
	/**
	 *  Archives a chat. decisions.id=739: explicit action only, never
	 *  implicit or bundled with create_chat -- see that command's own doc.
	 */
	archiveChat: (userId: string, personaId: string, chatId: string) => typedError<null, string>(__TAURI_INVOKE("archive_chat", { userId, personaId, chatId })),
};

/* Types */
export type ActiveBoardResponse = {
	topics: TopicInfo[],
	/**
	 *  IA_SPEC Section 2a/2b, decisions.id=712. Subset of `topics` whose
	 *  Focus type declared a high_priority_trigger that has fired for that
	 *  topic's anchor date. Additive, not exclusive of `topics` -- the
	 *  frontend (not yet built) owns rendering/dedup between the bordered
	 *  high-priority container and the full list.
	 */
	high_priority: TopicInfo[],
};

export type CapabilityProfileResponse = {
	installed_models: string[],
	/**
	 *  Release 1: "pending" | "unavailable" only.
	 *  "complete" requires evaluation/scores DB port (post-Release 1).
	 *  STUB: recommended_routing omitted until scores DB is ported.
	 */
	benchmark_status: string,
};

export type ChatInfo = {
	id: string,
	persona_id: string,
	context_key: string,
	title: string | null,
	archived_at: string | null,
	created_at: string,
	last_message_at: string,
};

export type CreatePersonaRequest = {
	user_id: string,
	name: string,
	color: string | null,
	persona_type: string | null,
};

export type CreatePersonaResponse = {
	persona_id: string,
};

/**
 *  Replaces ordinal tier comparisons at the five capability-gate call sites
 *  named in Part 6e: "may this step's execution leave the device at all,"
 *  decoupled from the old routing_tier==3 "pause for user handoff" signal
 *  (see StepDefinition::requires_user_handoff) and from the abstraction axis
 *  (focus_settings.privacy_tier, items.id=444 — untouched by this enum).
 * 
 *  Declaration order IS the ordering derive(Ord) uses — local_only is the
 *  tightest, unrestricted the loosest. anonymous_preferred is new: it never
 *  existed as a tier number (Part 6b), so from_legacy_tier() can never
 *  produce it — only a Focus/step authored directly against this enum can.
 * 
 *  Style mirrors NamedPolicy (persistence/focus_provider_criteria_store.rs):
 *  as_str()/from_str()-shaped helpers, snake_case serde.
 */
export type ExternalAccess = "local_only" | "anonymous_required" | "anonymous_preferred" | "unrestricted";

/**
 *  IPC gap: dormancy_state still missing -- split to items.id=256 (see
 *  module header). last_used closed by items.id=237.
 */
export type FocusInfo = {
	focus_id: string,
	focus_profile: string,
	context_flow: string,
	library_visibility: string,
	privacy_tier: number,
	max_permitted_tier: ExternalAccess,
	updated_at: string,
	/**
	 *  Most recent focus_runs.started_at for this Focus (outputs.db), or
	 *  None if it has never run or outputs.db isn't reachable with the
	 *  supplied key_hex. NOT the same as updated_at (settings-edit time).
	 */
	last_used: string | null,
};

/**
 *  IPC-safe projection of Gate3Result — Gate3Result itself derives neither
 *  Serialize nor specta::Type (it's an internal gate3.rs/executor.rs return
 *  type). Field-for-field mirror; see Gate3Result's own doc comments for
 *  what each bool means.
 */
export type Gate3ReviewResult = {
	approved: boolean,
	blocked: boolean,
	pending_consent: boolean,
	timeout: boolean,
	plain_language: string | null,
	target_tier: number | null,
	space_max_permitted_tier: ExternalAccess | null,
};

export type GetPendingCrossPersonaConfirmationsRequest = {
	user_id: string,
	persona_id: string,
};

export type GetRunOutputResponse = {
	content: string,
	output_type: string,
	sensitivity: string,
};

export type GroupSyncSettingsInfo = {
	folder_path: string,
	last_synced_at: string | null,
	last_error: string | null,
	updated_at: string,
};

export type HealthResponse = {
	ollama: ProviderHealth,
	/**
	 *  "system" | "sidecar" | "unavailable".
	 *  Set during app setup by OllamaSidecar::ensure_available().
	 *  "unavailable" is returned during the brief startup detection window.
	 */
	ollama_source: string,
	/**
	 *  True iff an active user-global key exists for ANY Tier 1.5 provider
	 *  (providers.provider_type='cloud_inference_api' -- items.id=430; was a
	 *  hardcoded ["mistral","groq"] array before this) -- a capability-status
	 *  signal ("is Tier 1.5 usable at all," e.g. for an onboarding nudge),
	 *  not a report of which provider is active. Provider *selection* at
	 *  execution time is a separate concern, wired through
	 *  user_provider_preference_store::resolve_preference() (items.id=432) --
	 *  out of scope for this field, there is no per-provider consumer
	 *  downstream to feed. False, not an error, when no session is resident
	 *  -- get_health must stay callable pre-login (Ollama status has no such
	 *  requirement).
	 */
	tier2_configured: boolean,
};

export type MessageInfo = {
	id: string,
	context_key: string,
	sender: string,
	content: string,
	focus_run_id: string | null,
	gate3_review_status: string | null,
	created_at: string,
};

/**
 *  Placeholder request/response shape for commands that are declared but not
 *  yet built.
 * 
 *  Why this exists (items.id=27): five stub commands
 *  (onboarding::get_onboarding_focus_suggestions,
 *  onboarding::submit_onboarding_focus_selection,
 *  focus_builder::get_focus_builder_session,
 *  focus_builder::submit_focus_builder_step, tier2::get_tier2_config)
 *  previously used serde_json::Value as an argument or return type.
 *  serde_json::Value is self-referential (Array(Vec<Value>),
 *  Object(Map<String, Value>)), and specta's TypeScript exporter recurses
 *  through it without terminating -- confirmed empirically: excluding exactly
 *  those five commands makes the export succeed, and a 64 MB stack does not
 *  help.
 * 
 *  These commands all return Err("not_implemented") today and have no designed
 *  payload shape, so serde_json::Value was a placeholder rather than a decided
 *  contract. This type says that explicitly instead. Each of the five should
 *  be given its real request/response struct when its feature is designed --
 *  this is deliberately not a contract to build against.
 * 
 *  UPDATE (items.id=185, 2026-08-02): tier2::get_tier2_config now has a real
 *  return type (commands::tier2::Tier2Config) and no longer uses this
 *  placeholder -- four of the original five remain unbuilt.
 * 
 *  UPDATE (items.id=229, 2026-08-09): auth::get_recovery_key_display also
 *  stopped using this placeholder (commands::auth::RecoveryKeyDisplay) --
 *  it was never one of the original five (it started using this type later,
 *  in commit dddc086/items.id=205, after this doc comment was written), so
 *  its removal doesn't change the "four of five" count above.
 */
export type NotImplementedPlaceholder = Record<string, never>;

export type OutputInfo = {
	id: string,
	focus_run_id: string,
	output_type: string,
	/**
	 *  NULL for an ingested document stored as opaque bytes -- see
	 *  has_original_document. See output_store::OutputRecord's own doc
	 *  comment.
	 */
	content: string | null,
	sensitivity: string,
	status: string,
	created_at: string,
	/**  'qr_generated' | 'external_ingested' (items.id=383). */
	source: string,
	project_entity_id: string | null,
	focus_slug: string | null,
	original_filename: string | null,
	/**
	 *  Derived from storage_path.is_some() -- whether get_ingested_document_bytes
	 *  (commands/ingest.rs) can retrieve a real original file for this output.
	 */
	has_original_document: boolean,
};

/**
 *  The four modifier keys a browser `PointerEvent`/`WheelEvent` reports as
 *  separate booleans (`shiftKey`/`ctrlKey`/`altKey`/`metaKey`) -- forwarded
 *  as-is by `forward_pane_mouse_click`/`_move`/`_wheel` rather than
 *  pre-converted to CEF's own bit-flag values client-side, so the one place
 *  that knows CEF's actual flag constants stays in pane_host.rs
 *  (`cef_modifiers_from_dom`).
 */
export type PaneEventModifiers = {
	shift: boolean,
	ctrl: boolean,
	alt: boolean,
	meta: boolean,
};

/**
 *  Mirrors `cef::MouseButtonType`'s 3-button model -- not reused directly
 *  since that type isn't `specta::Type`. The frontend maps a DOM
 *  `PointerEvent.button` (0/1/2) to this before sending; button values with
 *  no CEF equivalent (DOM also reports 3/4 for back/forward) are simply not
 *  forwarded, same policy `cef_mouse_button_from_gdk` already applied to
 *  GDK's own out-of-range button numbers.
 *  Mirrors `cef::KeyEventType`'s 3 variants used here -- not reused directly
 *  for the same reason `PaneMouseButton` isn't (that type isn't
 *  `specta::Type`). No `Char`-vs-`RawKeyDown` ambiguity on the wire: the
 *  frontend sends both explicitly for a printable keypress (see
 *  `forward_pane_key`'s own doc), this enum just names which one a given
 *  call is.
 */
export type PaneKeyEventType = "RawKeyDown" | "Char" | "KeyUp";

/**
 *  `Vec`, not `HashMap`, to match this codebase's existing IPC-struct
 *  convention -- no command signature anywhere else uses `HashMap`.
 */
export type PaneLayoutEntry = {
	provider_id: string,
	rect: PaneRectFraction,
};

export type PaneMouseButton = "Left" | "Middle" | "Right";

/**
 *  One pane's target region, as a fraction (0..1) of the main window's own
 *  *content* area -- not absolute screen pixels. Dimensionless on purpose:
 *  the frontend computes this from plain DOM geometry
 *  (`getBoundingClientRect()` / `window.innerWidth`/`innerHeight`), with no
 *  need for `devicePixelRatio` or a Tauri window-position API call. Under
 *  single-window compositing (items.id=202 real positioning fix,
 *  2026-08-07, see pane_host.rs) this fraction is multiplied directly
 *  against GTK's own live `GLArea` size inside `RenderState::render()` --
 *  no Rust-side window-geometry query is involved at all, so a window
 *  *move* alone stays correctly synced for free (GTK relayouts the GLArea
 *  as an ordinary child widget), and even a resize only needs the GLArea's
 *  own `resize` signal, not anything from `main.rs`.
 */
export type PaneRectFraction = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

/**
 *  IPC-safe projection of an entity_facts row pending cross-Persona
 *  confirmation (decisions.id=546, decisions.id=639, items.id=27).
 *  field_value is intentionally absent -- mirrors PersonalFieldInfo's
 *  no-raw-values convention in commands/personal.rs.
 */
export type PendingCrossPersonaFact = {
	/**
	 *  entity_facts.id -- pass this back in
	 *  SubmitFocusRunRequest.confirmed_cross_persona_fact_ids for any fact
	 *  the user approves.
	 */
	fact_id: string,
	entity_id: string | null,
	field_name: string,
	sensitivity: string,
	/**
	 *  The Persona instance this fact originated in (decisions.id=546).
	 *  Always Some for a row with cross_persona_export=true -- the DB CHECK
	 *  constraint on entity_facts (personal_001.sql) guarantees this.
	 */
	origin_persona_id: string | null,
};

/**
 *  IPC gap: privacy defaults still missing (post-Release 1, not this item's
 *  scope -- see module header). color/focus_count closed by items.id=237.
 */
export type PersonaInfo = {
	id: string,
	display_name: string,
	persona_type: string,
	created_at: string,
	color: string | null,
	/**
	 *  i32, not Persona.focus_count's i64 -- specta forbids exporting
	 *  BigInt-style types (i64/u64/...) to TypeScript.
	 */
	focus_count: number,
};

export type PersonaShareSyncSettingsInfo = {
	role: string,
	folder_path: string,
	last_synced_at: string | null,
	last_pushed_at: string | null,
	last_content_hash: string | null,
	last_error: string | null,
	updated_at: string,
};

export type PersonaViewShareSyncSettingsInfo = {
	folder_path: string,
	last_error: string | null,
	updated_at: string,
};

/**  IPC-safe projection of PersonalField. field_value is intentionally absent. */
export type PersonalFieldInfo = {
	field_name: string,
	sensitivity: string,
	/**  Abstracted display value for Tier 2 routing contexts. */
	abstraction_tier2: string,
	/**  Abstracted display value for Tier 3 routing contexts. */
	abstraction_tier3: string,
};

/**
 *  items.id=465 (shared_016.sql): whether a provider's privacy posture is
 *  backed by contractual language (DPA/Services Agreement) or is merely
 *  descriptive policy prose with no contractual commitment. Human-curated
 *  only, same as privacy_guardian_default_level -- never derived from
 *  documentation_gate's freeform research text.
 */
export type PrivacyCommitmentBasis = "contractual" | "policy_only";

/**
 *  privacy_guardian_default_level: deliberately parallel to ReviewTier's
 *  own three values (conductor/privacy/types.rs), same reasoning
 *  risk_rating already established (shared_012.sql).
 */
export type PrivacyGuardianDefaultLevel = "low" | "medium" | "high";

export type ProviderHealth = {
	provider: string,
	status: ProviderStatus,
	/**  ISO 8601 UTC string. */
	checked_at: string,
	error: string | null,
	available_models?: string[],
};

export type ProviderStatus = "available" | "degraded" | "unavailable";

/**
 *  items.id=406 (decisions.id=755): the provider-selection re-check
 *  trigger's request. `newly_active_provider_ids` is whatever the rail
 *  reports as active/laid-out at the moment of this call -- same
 *  PaneLayoutState-backed source of truth request_tier3_gate3_review
 *  itself reads, just supplied here explicitly since this command fires
 *  from a provider-activation event, not a fresh gate3 draft-review pass.
 */
export type RecheckTier3ProviderSelectionRequest = {
	user_id: string,
	persona_id: string,
	message_id: string,
	newly_active_provider_ids: string[],
};

/**
 *  One-time recovery mnemonic display. Never persisted anywhere past this
 *  response -- QR holds no copy of `mnemonic` or the entropy it was derived
 *  from once this call returns (Section 5/8.5 invariant).
 */
export type RecoveryKeyDisplay = {
	mnemonic: string,
};

/**
 *  items.id=416 (decisions.id=766): a native copy gesture on ChatPane's
 *  message transcript -- content_text is the concatenated text of whatever
 *  the user selected (one message or a span across several), supplied
 *  directly by the frontend rather than looked up by message_id, since a
 *  cross-message selection has no single message row to read from.
 */
export type RequestChatCopyGate3ReviewRequest = {
	user_id: string,
	persona_id: string,
	content_text: string,
};

export type RequestTier3Gate3ReviewRequest = {
	user_id: string,
	persona_id: string,
	message_id: string,
};

export type ResolveTier3Gate3ReviewRequest = {
	user_id: string,
	persona_id: string,
	message_id: string,
	/**
	 *  "approved" | "withheld" -- the two terminal states a resolved
	 *  consent review can reach. "drafted"/"pending-review" are gate3's own
	 *  transitions (request_tier3_gate3_review writes those), not valid
	 *  input here.
	 */
	status: string,
};

export type ResumeRunRequest = {
	run_id: string,
	user_id: string,
	persona_id: string,
};

/**
 *  Bundled to keep send_message's own parameter count under specta's 10-arg
 *  SpectaFn ceiling once confirmed_cross_persona_fact_ids (decisions.id=815,
 *  items.id=27) is added — the 4 Tauri-injected params (app_handle,
 *  scheduler, pool, key_registry) plus 7 business fields would otherwise be
 *  11. Mirrors SubmitFocusRunRequest's existing convention of one request DTO
 *  per command rather than a growing positional-arg list.
 */
export type SendMessageRequest = {
	user_id: string,
	persona_id: string,
	context_key: string,
	content: string,
	focus_id: string,
	gate3_track: boolean,
	/**
	 *  entity_facts.id values the user already confirmed this session, via
	 *  the frontend's pre-send commands::consent::get_pending_cross_persona_
	 *  confirmations() query + confirmation UI, BEFORE calling send_message.
	 *  Threaded straight into SubmitFocusRunRequest — previously hardcoded to
	 *  vec![] here, which silently omitted every legitimate cross-Persona
	 *  export on every QR Chat message (decisions.id=815's rescoping of this
	 *  item). No is_quick_ask branch: decisions.id=815 holds Quick Ask to the
	 *  identical standard as a named Focus run.
	 */
	confirmed_cross_persona_fact_ids: string[],
};

/**
 *  The current session's user identity, for get_session (items.id=267).
 *  Deliberately excludes master_key/key_hex -- CLAUDE.md's "Master key
 *  never persisted" rule has no IPC-boundary carve-out.
 */
export type SessionInfo = {
	user_id: string,
	display_name: string,
	role: string,
	is_primary: boolean,
};

export type StoreIngestedDocumentResponse = {
	output_id: string,
};

export type SubmitConsentDecisionRequest = {
	run_id: string,
	user_id: string,
	persona_id: string,
	/**  "approved" | "declined" */
	decision: string,
};

export type SubmitElementConsentDecisionRequest = {
	run_id: string,
	user_id: string,
	persona_id: string,
	/**
	 *  JSON-serialized Vec<ElementDecision> produced by the frontend.
	 *  Expected shape per element:
	 *    { "span_id": string, "decision": "generalize"|"keep_private"|"release_original",
	 *      "suggestion_text": string|null, "user_modified_text": string|null }
	 *  The command layer does not deserialize this -- it is passed through to
	 *  write_element_consent_decisions() as-is (D6-362 IPC boundary rule).
	 */
	decisions_json: string,
};

export type SubmitExtractConfirmRequest = {
	run_id: string,
	user_id: string,
	persona_id: string,
	/**
	 *  JSON-serialized Vec<ExtractConfirmDecision>.
	 *  Shape per element:
	 *    { "candidate_id": i64, "confirmed": bool,
	 *      "extracted_value": string, "confirmed_value": string|null }
	 *  confirmed_value must be non-null when confirmed==true.
	 */
	decisions_json: string,
};

export type SubmitFloorConsentDecisionRequest = {
	run_id: string,
	user_id: string,
	persona_id: string,
	abstraction_tier: number,
	/**  "proceed" | "cancel" */
	decision: string,
	/**  If true, saves as standing floor consent preference (D5-152). */
	save_preference: boolean,
};

export type SubmitFocusRunRequest = {
	focus_id: string,
	user_input: string,
	user_id: string,
	persona_id: string,
	topic_id: string | null,
	/**
	 *  entity_facts.id values the user approved via the pre-Focus-start
	 *  cross-Persona confirmation flow (decisions.id=546, decisions.id=639,
	 *  items.id=27) -- obtained by calling
	 *  commands::consent::get_pending_cross_persona_confirmations() before
	 *  this command. Any cross_persona_export=true fact whose id is absent
	 *  here is omitted from context, not blocked (declined-or-unasked case).
	 *  Empty vec is valid -- most runs have no pending cross-Persona facts.
	 */
	confirmed_cross_persona_fact_ids: string[],
};

export type SubmitFocusRunResponse = {
	run_id: string,
};

/**
 *  items.id=92 -- the user's proceed/cancel answer to a FrictionGateDetail
 *  the frontend received from a blocked update_focus_settings call.
 * 
 *  original_request carries the FULL originally-attempted settings change
 *  (not just the two gate-relevant fields) so that on decision="proceed"
 *  this command can apply the whole update in one call -- a real settings
 *  screen may bundle a gate-tripping field change together with
 *  non-gate-tripping ones (e.g. privacy_tier loosening alongside a
 *  context_flow change), and both must land together, not in two separate
 *  writes the frontend has to sequence itself.
 */
export type SubmitFrictionGateDecisionRequest = {
	/**  "proceed" | "cancel" */
	decision: string,
	original_request: UpdateFocusSettingsRequest,
};

export type SubscriptionStatus = "free" | "paid";

/**
 *  Non-secret Tier 2 configuration state -- never carries the credential
 *  itself. `configured` is true iff an active user-global tier2 key exists
 *  for `provider`.
 */
export type Tier2Config = {
	provider: string,
	configured: boolean,
	expires_at: string | null,
};

/**
 *  Selector-screen-facing provider summary. `lane` matches the frontend's
 *  `ProviderLane` string type (tier3AccessConfig.ts) verbatim -- no further
 *  transformation needed on the TypeScript side.
 * 
 *  items.id=427: providers has no tier column any more (Part 1's core
 *  rule -- tier is a display label only, never stored). `lane` is now
 *  derived here, at the display layer, from `provider_type` instead --
 *  exactly the pattern the spec permits ("tier labels computed only at the
 *  display layer"). Output is byte-identical to the old tier-based
 *  derivation for the 4 known providers; a future provider_type this match
 *  doesn't recognize falls back to the raw provider_type string, which
 *  won't satisfy the frontend's closed `'tier2' | 'tier3'` type -- that's
 *  Part 3c/5a's problem to solve when a new lane is actually needed, not
 *  this one.
 */
export type Tier3ProviderSummary = {
	id: string,
	display_name: string,
	lane: string,
	login_required: boolean,
	is_anonymous: boolean,
	privacy_guardian_default_level: PrivacyGuardianDefaultLevel | null,
	/**
	 *  items.id=465: whether QR itself recommends this provider, within its
	 *  own provider_type slot -- not a cross-slot ranking (see
	 *  provider_store::Provider::qr_recommended's own doc).
	 */
	qr_recommended: boolean,
	/**
	 *  items.id=465: throughput/latency class, nullable. Serialized to a
	 *  JSON string rather than carried as serde_json::Value -- that type is
	 *  self-referential and specta's TypeScript exporter recurses through
	 *  it without terminating (see commands/mod.rs's PlaceholderPayload doc
	 *  for the same constraint hitting this codebase before). The frontend
	 *  JSON.parse()s this field if it needs the structured shape.
	 */
	performance_profile: string | null,
	/**
	 *  items.id=465: contractual vs. policy-only privacy commitment,
	 *  human-curated, NULL until assessed.
	 */
	privacy_commitment_basis: PrivacyCommitmentBasis | null,
};

export type TopicInfo = {
	id: string,
	focus_id: string,
	lifecycle_state: string,
	display_name: string,
	updated_at: string,
};

export type UpdateFocusSettingsRequest = {
	persona_id: string,
	focus_id: string,
	context_flow: string | null,
	library_visibility: string | null,
	privacy_tier: number | null,
	max_permitted_tier: ExternalAccess | null,
	focus_profile: string | null,
};

export type UpdatePersonalFieldRequest = {
	persona_id: string,
	user_id: string,
	field_name: string,
	value: string,
	/**
	 *  Sensitivity of the field value. Defaults to "personal" if omitted.
	 *  Validation (general/personal/medical/financial) is enforced by the store.
	 */
	sensitivity: string | null,
};

export type UpdateTopicStateRequest = {
	topic_id: string,
	user_id: string,
	persona_id: string,
	state: string,
};

export type UserPreference = "preferred" | "allowed" | "declined";

export type UserProviderPreference = {
	id: string,
	user_id: string,
	/**
	 *  NULL = account-wide default (Part 2b's NULL-means-account-wide
	 *  convention, mirroring user_capabilities).
	 */
	persona_id: string | null,
	/**  NULL = Persona-wide default; set = Focus-specific override. */
	focus_id: string | null,
	provider_id: string,
	login_available: boolean,
	user_preference: UserPreference,
	enabled_at: string | null,
	declined_at: string | null,
	local_model_version: string | null,
	installed_at: string | null,
	last_verified_at: string | null,
	subscription_status: SubscriptionStatus | null,
	created_at: string,
};

/**
 *  IPC projection of voice profile. The store may contain additional attributes
 *  beyond these three; they are intentionally dropped at the IPC boundary.
 *  The IPC surface specifies tone, formality, length_preference only.
 */
export type VoiceProfileInfo = {
	tone: string,
	formality: string,
	length_preference: string,
};

/**
 *  items.id=364: a pane's own Ctrl+=/Ctrl+-/Ctrl+0 shortcuts, intercepted by
 *  the frontend (`PaneHitLayer.tsx`) before they'd otherwise reach CEF as
 *  ordinary forwarded key events -- CEF's Chrome-runtime browser has no
 *  window chrome of its own to interpret these as a zoom accelerator (that's
 *  normally a browser-UI concern, not something Blink handles unprompted),
 *  so the host app applies the zoom explicitly via
 *  `BrowserHost::set_zoom_level` instead (see `adjust_pane_zoom`'s own doc).
 */
export type ZoomDirection = "In" | "Out" | "Reset";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

