#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::sync::Arc;

use tauri::Manager;
use tokio::sync::{Mutex, RwLock};

use quietrabbit_lib::conductor::concurrency::ConductorScheduler;
use quietrabbit_lib::ipc::specta_builder;
use quietrabbit_lib::ollama_sidecar::{OllamaSidecar, OllamaSource};
use quietrabbit_lib::providers::ollama_client::OllamaClient;

#[tokio::main]
async fn main() {
    let scheduler = Arc::new(ConductorScheduler::new());
    // OllamaClient is stateless (three reqwest::Client instances, no mutable
    // state). Tauri State provides shared immutable access -- no Arc wrapping
    // needed beyond what Tauri already does internally.
    let ollama_client = OllamaClient::new();

    // tauri-specta command surface (items.id=27). The command list itself
    // lives in quietrabbit_lib::ipc so the binding-export drift test can run
    // under `cargo test --lib`. TypeScript bindings are generated by that
    // test, not at runtime -- there is no frontend to consume them yet.
    let builder = specta_builder();

    tauri::Builder::default()
        .manage(scheduler)
        .manage(ollama_client)
        // OllamaSource: initialized to Unavailable; the setup task writes the
        // real value after detect-first completes. get_health() reads via
        // read lock — zero contention after the first ~2 s of startup.
        .manage(RwLock::new(OllamaSource::Unavailable))
        // OllamaSidecar: holds the child process if a sidecar was started.
        // Mutex required because tokio::process::Child is not Sync.
        // Lock is held across ensure_available() (~0–7 s at startup only).
        .manage(Mutex::new(OllamaSidecar::new()))
        .setup(|app| {
            // Detection runs in a spawned task — setup() is synchronous.
            // OllamaSource stays Unavailable until detection completes
            // (typically < 2 s on Garuda where system Ollama is running).
            let handle = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                let resource_dir = match handle.path().resource_dir() {
                    Ok(p) => p,
                    Err(e) => {
                        log::warn!("main: could not resolve resource_dir: {e}");
                        return;
                    }
                };

                let source = {
                    let sidecar_state = handle.state::<Mutex<OllamaSidecar>>();
                    let mut sidecar = sidecar_state.lock().await;
                    sidecar.ensure_available(&resource_dir).await
                };

                let source_state = handle.state::<RwLock<OllamaSource>>();
                *source_state.write().await = source;
            });
            Ok(())
        })
        .on_window_event(|window, event| {
            if let tauri::WindowEvent::CloseRequested { .. } = event {
                // Stop the sidecar on window close. kill_on_drop(true) is the
                // crash-exit safety net; this provides the graceful path with
                // logging. Spawned without await — window closes immediately.
                // TODO: handle RunEvent::Exit for headless/multi-window support.
                log::info!("main: window close requested — stopping Ollama sidecar");
                let handle = window.app_handle().clone();
                tauri::async_runtime::spawn(async move {
                    let sidecar_state = handle.state::<Mutex<OllamaSidecar>>();
                    let mut sidecar = sidecar_state.lock().await;
                    sidecar.stop().await;
                });
            }
        })
        // Command surface + generated TypeScript contract: see
        // quietrabbit_lib::ipc::specta_builder(). The authoritative command
        // list lives there, not here -- keeping it in one home means the
        // exported bindings and the live handler can never disagree.
        .invoke_handler(builder.invoke_handler())
        .run(tauri::generate_context!())
        .expect("error while running Quiet Rabbit");
}
