#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::sync::Arc;

use tauri::Manager;
use tokio::sync::{Mutex, RwLock};

use quietrabbit_lib::conductor::concurrency::ConductorScheduler;
use quietrabbit_lib::conductor::privacy::privacy_filter;
use quietrabbit_lib::ipc::specta_builder;
use quietrabbit_lib::ollama_sidecar::{OllamaSidecar, OllamaSource};
use quietrabbit_lib::providers::ollama_client::OllamaClient;

/// Plain, synchronous entry point -- NOT `#[tokio::main]`.
///
/// CEF's subprocess dispatch (`tier3_pane::dispatch_cef_subprocess`) must
/// run before Tokio initializes anything in this process. Per Tokio's own
/// documentation, forking without an immediate exec is only supported
/// "before the parent process has used Tokio in any way" -- and CEF's
/// multi-process architecture forks+execs helper processes internally.
/// `#[tokio::main] async fn main()` would enter the Tokio runtime as the
/// first thing that happens, before this dispatch could run. See
/// tier3_pane::bootstrap module docs for the full rationale.
///
/// Restructured 2026-08-01 for items.id=3 States 4-5 (Phase A), approved by
/// Jason -- the async body that used to be the whole of `main()` is now
/// `async_main()`, entered via a manually-constructed Tokio runtime only
/// after CEF subprocess dispatch has confirmed this is the real
/// browser-process invocation.
fn main() {
    // Diagnostic-only for Phase A verification -- pre-existing log:: calls
    // in this codebase (e.g. ollama_sidecar.rs) had no registered backend
    // before this, confirmed by an empty log file during the first Phase A
    // run despite RUST_LOG being set. Not evaluating whether this should
    // become the project's permanent logging setup -- flagged to Chat-PM
    // rather than decided here.
    env_logger::init();

    if quietrabbit_lib::tier3_pane::dispatch_cef_subprocess() {
        // This invocation was a CEF-spawned helper process (renderer, GPU,
        // utility, etc). CEF's own subprocess entry point has already run
        // to completion inside dispatch_cef_subprocess(). Nothing else in
        // this binary -- no Tokio, no Tauri -- should run for this
        // invocation.
        return;
    }

    tokio::runtime::Runtime::new()
        .expect("quietrabbit: failed to build Tokio runtime")
        .block_on(async_main());
}

async fn async_main() {
    let scheduler = Arc::new(ConductorScheduler::new());
    // OllamaClient is stateless (three reqwest::Client instances, no mutable
    // state). Tauri State provides shared immutable access -- no Arc wrapping
    // needed beyond what Tauri already does internally.
    let ollama_client = OllamaClient::new();

    // tauri-specta command surface (items.id=27). The command list itself
    // lives in quietrabbit_lib::ipc so the binding-export drift test can run
    // under `cargo test --lib`. TypeScript bindings are generated by that
    // test, not at runtime -- there is no frontend to consume them yet.
    let builder = specta_builder();

    // PaneHost (GTK objects throughout) is deliberately NOT stored via
    // Tauri's .manage()/.state() -- Tauri's Manager::state<T>() requires
    // T: Send + Sync, and GTK types aren't (same class of constraint
    // winit's X11 IME pointers used to impose here). PaneHost instead lives
    // in a main-thread-only thread-local (see tier3_pane::pane_host's own
    // module docs on why, and how commands::tier3_pane reaches it via
    // AppHandle::run_on_main_thread instead of Tauri-managed state).
    let app = tauri::Builder::default()
        .manage(scheduler)
        .manage(ollama_client)
        .manage(quietrabbit_lib::commands::tier3_pane::PaneLayoutState::default())
        // OllamaSource: initialized to Unavailable; the setup task writes the
        // real value after detect-first completes. get_health() reads via
        // read lock — zero contention after the first ~2 s of startup.
        .manage(RwLock::new(OllamaSource::Unavailable))
        // OllamaSidecar: holds the child process if a sidecar was started.
        // Mutex required because tokio::process::Child is not Sync.
        // Lock is held across ensure_available() (~0–7 s at startup only).
        .manage(Mutex::new(OllamaSidecar::new()))
        // KeyRegistry: single-slot in-memory master-key registry (items.id=
        // 205, Architecture/AUTH_MULTIUSER_ARCHITECTURE.md Section 4.2).
        // Encapsulated type -- its own internal Mutex is not exposed
        // directly (see auth::registry module header). Default::default()
        // starts with an empty slot; login() (a later step) populates it.
        .manage(quietrabbit_lib::auth::registry::KeyRegistry::default())
        .setup(|app| {
            // Must run synchronously here, before any command handler could
            // touch persistence::migrations::get_data_root() -- every prior
            // caller of that function was test code, which points
            // QR_DATA_ROOT at a tempdir itself (see test_support.rs);
            // nothing in the real app ever set it, so any real IPC call
            // that touched the DB layer (get_health, listActiveProviders,
            // ...) panicked on a tokio worker thread with "QR_DATA_ROOT
            // environment variable not set" the first time this app was
            // actually driven end-to-end through a live window (found via
            // WAYLAND_DEBUG repro session, 2026-08-08 -- see items.id=227
            // investigation). Derived from the same app_data_dir() Tauri
            // already resolves for the CEF root_cache_path below, so both
            // land under the same per-install data directory.
            match app.path().app_data_dir() {
                Ok(dir) => {
                    if let Err(e) = std::fs::create_dir_all(&dir) {
                        log::error!(
                            "main: could not create app_data_dir {dir:?} for \
                             QR_DATA_ROOT: {e} — persistence commands will panic"
                        );
                    } else {
                        std::env::set_var("QR_DATA_ROOT", &dir);
                    }
                }
                Err(e) => log::error!(
                    "main: could not resolve app_data_dir for QR_DATA_ROOT: {e} \
                     — persistence commands will panic until this is set"
                ),
            }

            // Must run synchronously here, before any command handler could
            // trigger gate3's first Privacy Filter classification — ggml's
            // backend loader (see privacy_filter.rs) runs once, lazily, on
            // first use, and is cached for the process lifetime. Ollama
            // detection below is spawned async since it's not similarly
            // latch-once; this call is cheap and must not race it.
            match app.path().resource_dir() {
                Ok(dir) => privacy_filter::set_backend_dir(dir.join("ggml-backends")),
                Err(e) => log::warn!(
                    "main: could not resolve resource_dir for Privacy Filter \
                     backend dir: {e} — falling back to build-time dev path"
                ),
            }

            // Detection runs in a spawned task — setup() is synchronous.
            // OllamaSource stays Unavailable until detection completes
            // (typically < 2 s on Garuda where system Ollama is running).
            let handle = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                let resource_dir = match handle.path().resource_dir() {
                    Ok(p) => p,
                    Err(e) => {
                        log::warn!("main: could not resolve resource_dir: {e}");
                        return;
                    }
                };

                let source = {
                    let sidecar_state = handle.state::<Mutex<OllamaSidecar>>();
                    let mut sidecar = sidecar_state.lock().await;
                    sidecar.ensure_available(&resource_dir).await
                };

                let source_state = handle.state::<RwLock<OllamaSource>>();
                *source_state.write().await = source;
            });
            Ok(())
        })
        // No Moved/Resized handling here anymore (items.id=202 real
        // positioning fix, 2026-08-07): that handler used to query
        // window.inner_position()/inner_size() and push the result through
        // a channel to re-sync each pane's separate OS window -- confirmed
        // broken on Wayland (pinned x=0,y=0 plus a wrong size on this dev
        // machine's KDE/Wayland session, consistent with
        // tauri-apps/tauri#12411/tao#566), and the exact code path this
        // rewrite deletes rather than patches. Every open pane now lives
        // inside GTK's own GLArea widget, in the SAME window -- GTK
        // relayouts it for free on window move/resize, no Rust-side
        // geometry query needed. Only CloseRequested is left to handle, so
        // this is an `if let`, not a `match` (clippy::single_match).
        .on_window_event(move |window, event| {
            if let tauri::WindowEvent::CloseRequested { .. } = event {
                // Stop the sidecar on window close. kill_on_drop(true) is the
                // crash-exit safety net; this provides the graceful path with
                // logging. Spawned without await — window closes immediately.
                // TODO: handle RunEvent::Exit for headless/multi-window support.
                log::info!("main: window close requested — stopping Ollama sidecar");
                let handle = window.app_handle().clone();
                tauri::async_runtime::spawn(async move {
                    let sidecar_state = handle.state::<Mutex<OllamaSidecar>>();
                    let mut sidecar = sidecar_state.lock().await;
                    sidecar.stop().await;
                });
            }
        })
        // Command surface + generated TypeScript contract: see
        // quietrabbit_lib::ipc::specta_builder(). The authoritative command
        // list lives there, not here -- keeping it in one home means the
        // exported bindings and the live handler can never disagree.
        .invoke_handler(builder.invoke_handler())
        .build(tauri::generate_context!())
        .expect("error while building Quiet Rabbit");

    // CEF init moved here (items.id=202 piece 5, 2026-08-04) from before
    // tauri::Builder::default() -- root_cache_path (CEF's global
    // Settings.root_cache_path, see bootstrap.rs docs) needs
    // app.path().app_data_dir(), which requires a built App/AppHandle and
    // does not exist before .build() returns. The prior placement's own
    // comment already claimed this ran "after Tauri's own window exists"
    // and noted "CEF itself does not need a Tauri window to exist first" --
    // this placement now actually matches that, rather than running before
    // tauri::Builder::default() was even constructed. PaneWindow itself no
    // longer needs this path (items.id=224 resolution, decisions.id=711 --
    // no more per-pane cache_path built under it), but CEF's global context
    // still does.
    let app_data_dir = app.path().app_data_dir().unwrap_or_else(|e| {
        log::warn!(
            "main: could not resolve app_data_dir for tier3_pane root_cache_path: {e} \
             -- falling back to a temp dir (persistence across restarts will not work \
             correctly at this fallback location)"
        );
        std::env::temp_dir().join("quietrabbit")
    });
    let root_cache_path = app_data_dir.join("tier3_pane_cache");
    // Uses multi_threaded_message_loop=true (see tier3_pane::bootstrap docs
    // for the full root-cause history) -- CEF runs its own UI thread
    // separately from Tauri's GTK main thread, which is what avoids the
    // GTK/GLib main-loop busy-poll that a same-thread external-pump
    // approach hit.
    let _cef_init = quietrabbit_lib::tier3_pane::bootstrap::initialize_cef(&root_cache_path);

    // Single-window GTK/wgpu pane host (items.id=202 real positioning fix,
    // 2026-08-07 -- see tier3_pane::pane_host's module docs for the full
    // architecture). Reparents Tauri's own webview widget into a
    // gtk::Overlay and adds the shared GLArea every open pane composites
    // into, on top of it, inside THIS window -- no separate OS window, no
    // separate winit event loop, and therefore none of the
    // window-position-query machinery that used to live in this file (the
    // deleted on_window_event Moved/Resized arm above, PhysicalRect,
    // sync_tx/sync_rx) or the freeze-bug heartbeat below it. Zero panes
    // exist yet -- installing the host creates nothing but the GLArea
    // widget itself; panes are created on demand via
    // pane_host::dispatch(PaneCommand::Open) in response to a real Tier 2/3
    // selection (commands::tier3_pane).
    //
    // FOUND THE HARD WAY (2026-08-07, manual verification): installing
    // right here -- between `.build()` returning and `.run()` starting --
    // panics: `app.get_webview_window("main")` returns `None`, even though
    // tauri.conf.json declares exactly one window and no other code path
    // ever removes it. The window is not yet registered as retrievable at
    // this point in Tauri's own startup sequence; `RunEvent::Ready`
    // ("Application ready", fired once the event loop has actually
    // started) is the documented, correct point to depend on a window
    // existing. `.build()` returning is not the same milestone.
    app.run(move |app_handle, event| {
        if let tauri::RunEvent::Ready = event {
            let main_window = app_handle
                .get_webview_window("main")
                .expect("quietrabbit: main window not found on RunEvent::Ready");
            let open_pane_count = quietrabbit_lib::tier3_pane::pane_host::install(
                &main_window,
                app_handle.clone(),
            );

            // Replaces the old freeze-bug heartbeat thread (a 16ms
            // run_on_main_thread(|| {}) loop whose entire purpose was
            // forcing tao's own blocking GTK loop to notice a SECOND,
            // GTK-invisible winit/Wayland connection -- see pane_host.rs's
            // module docs on why that whole problem class no longer
            // exists). This timeout is a real, first-class GSource on
            // GTK's own main loop -- not a workaround for a blind spot,
            // just the normal way to drive a periodic redraw. Gated on
            // open_pane_count > 0 for the same on-demand-cost reason as
            // before (items.id=223): a user who never opens Tier 2/3 pays
            // nothing here. 16ms matches the old cadence (~60fps) and
            // CEF's own windowless_frame_rate: 60 (pane_host.rs).
            let diag_tick = std::cell::Cell::new(0u64);
            glib::source::timeout_add_local(std::time::Duration::from_millis(16), move || {
                let count = open_pane_count.load(std::sync::atomic::Ordering::Relaxed);
                let tick = diag_tick.get() + 1;
                diag_tick.set(tick);
                if tick % 60 == 0 {
                    log::debug!("DIAG items.id=227: 16ms timeout tick={tick} open_pane_count={count}");
                }
                if count > 0 {
                    quietrabbit_lib::tier3_pane::pane_host::queue_draw();
                }
                glib::ControlFlow::Continue
            });
        }
    });
}
