#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::sync::Arc;

use tauri::Manager;
use tokio::sync::{Mutex, RwLock};

use quietrabbit_lib::conductor::concurrency::ConductorScheduler;
use quietrabbit_lib::conductor::privacy::privacy_filter;
use quietrabbit_lib::ipc::specta_builder;
use quietrabbit_lib::ollama_sidecar::{OllamaSidecar, OllamaSource};
use quietrabbit_lib::providers::ollama_client::OllamaClient;

/// Plain, synchronous entry point -- NOT `#[tokio::main]`.
///
/// CEF's subprocess dispatch (`tier3_pane::dispatch_cef_subprocess`) must
/// run before Tokio initializes anything in this process. Per Tokio's own
/// documentation, forking without an immediate exec is only supported
/// "before the parent process has used Tokio in any way" -- and CEF's
/// multi-process architecture forks+execs helper processes internally.
/// `#[tokio::main] async fn main()` would enter the Tokio runtime as the
/// first thing that happens, before this dispatch could run. See
/// tier3_pane::bootstrap module docs for the full rationale.
///
/// Restructured 2026-08-01 for items.id=3 States 4-5 (Phase A), approved by
/// Jason -- the async body that used to be the whole of `main()` is now
/// `async_main()`, entered via a manually-constructed Tokio runtime only
/// after CEF subprocess dispatch has confirmed this is the real
/// browser-process invocation.
fn main() {
    // Diagnostic-only for Phase A verification -- pre-existing log:: calls
    // in this codebase (e.g. ollama_sidecar.rs) had no registered backend
    // before this, confirmed by an empty log file during the first Phase A
    // run despite RUST_LOG being set. Not evaluating whether this should
    // become the project's permanent logging setup -- flagged to Chat-PM
    // rather than decided here.
    env_logger::init();

    if quietrabbit_lib::tier3_pane::dispatch_cef_subprocess() {
        // This invocation was a CEF-spawned helper process (renderer, GPU,
        // utility, etc). CEF's own subprocess entry point has already run
        // to completion inside dispatch_cef_subprocess(). Nothing else in
        // this binary -- no Tokio, no Tauri -- should run for this
        // invocation.
        return;
    }

    tokio::runtime::Runtime::new()
        .expect("quietrabbit: failed to build Tokio runtime")
        .block_on(async_main());
}

async fn async_main() {
    let scheduler = Arc::new(ConductorScheduler::new());
    // OllamaClient is stateless (three reqwest::Client instances, no mutable
    // state). Tauri State provides shared immutable access -- no Arc wrapping
    // needed beyond what Tauri already does internally.
    let ollama_client = OllamaClient::new();

    // tauri-specta command surface (items.id=27). The command list itself
    // lives in quietrabbit_lib::ipc so the binding-export drift test can run
    // under `cargo test --lib`. TypeScript bindings are generated by that
    // test, not at runtime -- there is no frontend to consume them yet.
    let builder = specta_builder();

    // PaneWindow is deliberately NOT stored via Tauri's .manage()/.state()
    // (found the hard way, 2026-08-01): winit::EventLoop on X11 holds raw
    // platform IME pointers (*mut _XIM/_XIC) that are not Send, and
    // Tauri's Manager::state<T>() requires T: Send + Sync. PaneWindow is
    // instead captured directly by the app.run() closure below, which owns
    // it on the main thread without needing it to cross a generic Send
    // boundary -- the correct fix per the type system's actual signal
    // (real thread affinity in winit's X11 backend), not a suppressed
    // unsafe impl Send. Window move/resize sync (on_window_event, a
    // separate closure) reaches PaneWindow via an mpsc channel rather than
    // shared state, for the same reason. `PaneWindow::proxy()` -- winit's
    // `EventLoopProxy` IS `Send + Sync` -- is what crosses that boundary
    // instead, managed as real Tauri state below (items.id=202 piece 5 /
    // items.id=223) so async IPC command handlers can request pane
    // open/close without touching PaneWindow itself.
    let (sync_tx, sync_rx) =
        std::sync::mpsc::channel::<quietrabbit_lib::tier3_pane::sync_window::PhysicalRect>();

    let app = tauri::Builder::default()
        .manage(scheduler)
        .manage(ollama_client)
        // OllamaSource: initialized to Unavailable; the setup task writes the
        // real value after detect-first completes. get_health() reads via
        // read lock — zero contention after the first ~2 s of startup.
        .manage(RwLock::new(OllamaSource::Unavailable))
        // OllamaSidecar: holds the child process if a sidecar was started.
        // Mutex required because tokio::process::Child is not Sync.
        // Lock is held across ensure_available() (~0–7 s at startup only).
        .manage(Mutex::new(OllamaSidecar::new()))
        // KeyRegistry: single-slot in-memory master-key registry (items.id=
        // 205, Architecture/AUTH_MULTIUSER_ARCHITECTURE.md Section 4.2).
        // Encapsulated type -- its own internal Mutex is not exposed
        // directly (see auth::registry module header). Default::default()
        // starts with an empty slot; login() (a later step) populates it.
        .manage(quietrabbit_lib::auth::registry::KeyRegistry::default())
        .setup(|app| {
            // Must run synchronously here, before any command handler could
            // trigger gate3's first Privacy Filter classification — ggml's
            // backend loader (see privacy_filter.rs) runs once, lazily, on
            // first use, and is cached for the process lifetime. Ollama
            // detection below is spawned async since it's not similarly
            // latch-once; this call is cheap and must not race it.
            match app.path().resource_dir() {
                Ok(dir) => privacy_filter::set_backend_dir(dir.join("ggml-backends")),
                Err(e) => log::warn!(
                    "main: could not resolve resource_dir for Privacy Filter \
                     backend dir: {e} — falling back to build-time dev path"
                ),
            }

            // Detection runs in a spawned task — setup() is synchronous.
            // OllamaSource stays Unavailable until detection completes
            // (typically < 2 s on Garuda where system Ollama is running).
            let handle = app.handle().clone();
            tauri::async_runtime::spawn(async move {
                let resource_dir = match handle.path().resource_dir() {
                    Ok(p) => p,
                    Err(e) => {
                        log::warn!("main: could not resolve resource_dir: {e}");
                        return;
                    }
                };

                let source = {
                    let sidecar_state = handle.state::<Mutex<OllamaSidecar>>();
                    let mut sidecar = sidecar_state.lock().await;
                    sidecar.ensure_available(&resource_dir).await
                };

                let source_state = handle.state::<RwLock<OllamaSource>>();
                *source_state.write().await = source;
            });
            Ok(())
        })
        .on_window_event(move |window, event| {
            match event {
                tauri::WindowEvent::CloseRequested { .. } => {
                    // Stop the sidecar on window close. kill_on_drop(true) is the
                    // crash-exit safety net; this provides the graceful path with
                    // logging. Spawned without await — window closes immediately.
                    // TODO: handle RunEvent::Exit for headless/multi-window support.
                    log::info!("main: window close requested — stopping Ollama sidecar");
                    let handle = window.app_handle().clone();
                    tauri::async_runtime::spawn(async move {
                        let sidecar_state = handle.state::<Mutex<OllamaSidecar>>();
                        let mut sidecar = sidecar_state.lock().await;
                        sidecar.stop().await;
                    });
                }
                tauri::WindowEvent::Moved(_) | tauri::WindowEvent::Resized(_) => {
                    // Phase A manual sync (see tier3_pane::sync_window docs
                    // for why this is manual rather than OS-level child-window
                    // reparenting). outer_position/outer_size are queried
                    // fresh rather than derived from the event payload, since
                    // WindowEvent::Moved/Resized report platform-specific
                    // coordinate spaces that don't uniformly match what
                    // outer_position()/outer_size() report.
                    //
                    // Sent via channel rather than shared state -- PaneWindow
                    // is not Send (see the comment above its construction),
                    // so it cannot be reached from this closure directly; the
                    // app.run() closure, which owns it on the main thread,
                    // drains this channel each MainEventsCleared tick.
                    if let (Ok(pos), Ok(size)) = (window.outer_position(), window.outer_size()) {
                        let rect = quietrabbit_lib::tier3_pane::sync_window::PhysicalRect {
                            x: pos.x,
                            y: pos.y,
                            width: size.width as i32,
                            height: size.height as i32,
                        };
                        // A closed/lagging receiver just means no sync this
                        // tick -- not a fatal condition for a fire-and-forget
                        // position update; the next move/resize event will
                        // simply try again.
                        let _ = sync_tx.send(rect);
                    }
                }
                _ => {}
            }
        })
        // Command surface + generated TypeScript contract: see
        // quietrabbit_lib::ipc::specta_builder(). The authoritative command
        // list lives there, not here -- keeping it in one home means the
        // exported bindings and the live handler can never disagree.
        .invoke_handler(builder.invoke_handler())
        .build(tauri::generate_context!())
        .expect("error while building Quiet Rabbit");

    // CEF init + PaneWindow construction moved here (items.id=202 piece 5,
    // 2026-08-04) from before tauri::Builder::default() -- root_cache_path
    // (both CEF's global Settings.root_cache_path and PaneWindow's own
    // per-provider cache_path base, see bootstrap.rs/sync_window.rs docs)
    // needs app.path().app_data_dir(), which requires a built App/AppHandle
    // and does not exist before .build() returns. The prior placement's own
    // comment already claimed this ran "after Tauri's own window exists"
    // and noted "CEF itself does not need a Tauri window to exist first" --
    // this placement now actually matches that, rather than running before
    // tauri::Builder::default() was even constructed.
    let app_data_dir = app.path().app_data_dir().unwrap_or_else(|e| {
        log::warn!(
            "main: could not resolve app_data_dir for tier3_pane root_cache_path: {e} \
             -- falling back to a temp dir (persistence across restarts will not work \
             correctly at this fallback location)"
        );
        std::env::temp_dir().join("quietrabbit")
    });
    let root_cache_path = app_data_dir.join("tier3_pane_cache");
    // Uses multi_threaded_message_loop=true (see tier3_pane::bootstrap docs
    // for the full root-cause history) -- CEF runs its own UI thread
    // separately from Tauri's GTK main thread, which is what avoids the
    // GTK/GLib main-loop busy-poll that a same-thread external-pump
    // approach hit.
    let _cef_init = quietrabbit_lib::tier3_pane::bootstrap::initialize_cef(&root_cache_path);
    // Phase B (items.id=202 piece 5 / items.id=223): zero panes exist yet --
    // PaneWindow::new no longer takes an initial URL or creates anything
    // eagerly. Panes are created on demand via the proxy managed below, in
    // response to a real Tier 2/3 selection -- see sync_window.rs docs.
    let mut pane_window =
        quietrabbit_lib::tier3_pane::sync_window::PaneWindow::new(root_cache_path);
    // EventLoopProxy IS Send + Sync (unlike PaneWindow itself, see the
    // .manage() comment above) -- this is what lets an async IPC command
    // handler (commands::tier3_pane, tokio-side) request a pane open/close
    // without needing access to PaneWindow's winit-thread-affine state.
    app.manage(pane_window.proxy());
    // Shared with the heartbeat thread below so it can gate its real cost
    // on whether any pane is actually open right now, rather than Phase
    // A's one-shot "exit once the single pane closes" latch -- items.id=223.
    let open_pane_count = pane_window.open_pane_count();

    // ROOT CAUSE + FIX (2026-08-04, items.id=202 freeze) -- read before
    // touching this again.
    //
    // SYMPTOM: the pane freezes (compositor marks it "Not Responding",
    // fractional/unsettled window geometry) after maximize/restore-style
    // interaction with the pane window specifically. Two prior fix attempts
    // (the RESIZE_DEBOUNCE in sync_window.rs) targeted a different trigger
    // (maximize-via-snap) and didn't touch this one. `gdb thread apply all
    // bt` during the freeze showed every thread legitimately idle -- no
    // deadlock, no lock contention.
    //
    // ROOT CAUSE, gdb-confirmed by breaking into a live freeze (process
    // launched as gdb's own child, so no ptrace_scope restriction applied):
    // the main thread was blocked inside tao's own
    // `tao::platform_impl::platform::event_loop::EventLoop::run_return`
    // (tao-0.35.3, linux/event_loop.rs:1044/1154), which on Linux drives its
    // loop via a genuinely BLOCKING `gtk_main_iteration_do(blocking: true)`
    // whenever `ControlFlow::Wait` (tao's default, and the only mode
    // Tauri's public API exposes) has nothing queued. Confirmed directly in
    // tao's own source (linux/event_loop.rs's `run_return`): with
    // `ControlFlow::Wait` and an empty event queue, the loop sets
    // `blocking = true` and does not fire `Event::MainEventsCleared` again
    // until *something* lands in that queue.
    //
    // `PaneWindow::pump()` below -- which services the pane's own,
    // completely separate `winit::event_loop::EventLoop` (its own Wayland
    // connection, its own `xdg_wm_base` ping/pong, its own CEF
    // `send_external_begin_frame()`, its own redraw) -- only ever runs from
    // inside `RunEvent::MainEventsCleared`. GTK's main context has no
    // visibility into the pane's separate connection at all, so whenever
    // the MAIN window is idle (no mouse movement, no timers, nothing GTK
    // itself needs to dispatch) -- which any interaction confined to the
    // pane window trivially produces -- tao's loop blocks indefinitely and
    // `pump()` simply never runs. Confirmed via the Wayland trace
    // (WAYLAND_DEBUG=1): the pane's connection goes completely silent (no
    // configure, no ack, no surface commit) for the same duration tao sits
    // blocked, then catches up in one burst the moment something wakes it.
    // This is also why prior `gdb` runs found every thread idle: blocking
    // on a real GTK/glib wait for an event that never arrives isn't a
    // deadlock from Rust's point of view -- there's no held lock to see.
    //
    // FIX: force tao's loop to wake on a steady cadence regardless of what
    // the main window is doing. `AppHandle::run_on_main_thread` is
    // implemented (tauri-runtime-wry) as a `tao::event_loop::EventLoopProxy
    // ::send_event` -- the same queue `run_return` checks -- so a periodic
    // no-op call here forces `MainEventsCleared` to keep firing on
    // approximately the same ~16ms cadence `PaneWindow::pump()` already
    // assumes for its own throttling, independent of the main window's own
    // activity.
    //
    // SCOPE (raised in review, 2026-08-04): this must not run for the app's
    // entire lifetime regardless of whether the pane is ever used --
    // TIER3_ACCESS_MODEL.md treats Tier 2/3 as something the user opens
    // deliberately, and an always-on 16ms wake for every user contradicts
    // the idle-CPU discipline decisions.id=700 already fought for (Finding
    // 1, the CPU-collision fix, this same code cluster).
    //
    // UPDATE (2026-08-04, items.id=223, same session as the multi-pane
    // refactor above): at the time this heartbeat was first added, no
    // pane-lifecycle hooks existed anywhere in tier3_pane/ -- PaneWindow was
    // constructed once, eagerly, at startup, and nothing ever tore it down,
    // so the only gate available was `WindowEvent::CloseRequested`'s
    // one-shot exit signal (`PaneWindow::running_flag()`, since removed).
    // Phase B's on-demand `PaneCommand::Open`/`Close` (sync_window.rs) is
    // that real lifecycle hook, and `open_pane_count` (below) is a live
    // count rather than a one-shot latch -- so this loop no longer exits
    // permanently on first close; it just skips the actual wake (the
    // `run_on_main_thread` call, which is what forces GTK's loop to keep
    // firing `MainEventsCleared`) on any tick where zero panes are open,
    // and resumes waking automatically the next time one opens. The OS
    // thread itself still sleeps for the app's entire lifetime -- cheaper
    // to leave one thread doing a 16ms `Relaxed` atomic load than to
    // spawn/kill it on every open/close and risk a start race.
    {
        let heartbeat_handle = app.handle().clone();
        std::thread::spawn(move || loop {
            std::thread::sleep(std::time::Duration::from_millis(16));
            if open_pane_count.load(std::sync::atomic::Ordering::Relaxed) == 0 {
                continue;
            }
            if heartbeat_handle.run_on_main_thread(|| {}).is_err() {
                break;
            }
        });
    }

    // Shared winit event loop interleaving (see tier3_pane::mod.rs docs on
    // the process/thread model decision): every currently-open pane's
    // winit machinery is pumped once per Tauri main-loop iteration, on
    // RunEvent::MainEventsCleared -- one pump() call regardless of pane
    // count (see PaneWindow::pump docs). CEF's own message loop runs
    // entirely on its own OS thread now (multi_threaded_message_loop=true)
    // and needs no interleaving from here at all -- see tier3_pane::bootstrap
    // docs. pane_window and sync_rx are moved into this closure (not
    // Tauri-managed state, per the Send constraint above) -- this closure
    // runs on the main thread for the app's entire lifetime, which is
    // exactly PaneWindow's required affinity.
    app.run(move |_app_handle, event| {
        if let tauri::RunEvent::MainEventsCleared = event {
            // Drain all pending sync updates (not just the latest) so a
            // burst of move/resize events during a drag doesn't leave any
            // pane visibly behind by more than one tick's worth of catch-up.
            // Applied to every currently-open pane (Phase A had exactly
            // one; Phase B may have zero to three) -- see PaneWindow::sync_to
            // docs for the placeholder (not yet Phase C real) layout math.
            while let Ok(rect) = sync_rx.try_recv() {
                for key in pane_window.pane_keys() {
                    pane_window.sync_to(&key, rect);
                }
            }
            pane_window.pump();
        }
    });
}
